// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notify.proto

package com.futu.opend.api.protobuf;

public final class Notify {
  private Notify() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code Notify.NotifyType}
   */
  public enum NotifyType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NotifyType_None = 0;</code>
     *
     * <pre>
     *无
     * </pre>
     */
    NotifyType_None(0, 0),
    /**
     * <code>NotifyType_GtwEvent = 1;</code>
     *
     * <pre>
     *OpenD运行事件通知
     * </pre>
     */
    NotifyType_GtwEvent(1, 1),
    ;

    /**
     * <code>NotifyType_None = 0;</code>
     *
     * <pre>
     *无
     * </pre>
     */
    public static final int NotifyType_None_VALUE = 0;
    /**
     * <code>NotifyType_GtwEvent = 1;</code>
     *
     * <pre>
     *OpenD运行事件通知
     * </pre>
     */
    public static final int NotifyType_GtwEvent_VALUE = 1;


    public final int getNumber() { return value; }

    public static NotifyType valueOf(int value) {
      switch (value) {
        case 0: return NotifyType_None;
        case 1: return NotifyType_GtwEvent;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NotifyType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<NotifyType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NotifyType>() {
            public NotifyType findValueByNumber(int number) {
              return NotifyType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.futu.opend.api.protobuf.Notify.getDescriptor().getEnumTypes().get(0);
    }

    private static final NotifyType[] VALUES = values();

    public static NotifyType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private NotifyType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Notify.NotifyType)
  }

  /**
   * Protobuf enum {@code Notify.GtwEventType}
   */
  public enum GtwEventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GtwEventType_None = 0;</code>
     *
     * <pre>
     *正常无错
     * </pre>
     */
    GtwEventType_None(0, 0),
    /**
     * <code>GtwEventType_LocalCfgLoadFailed = 1;</code>
     *
     * <pre>
     *加载本地配置失败
     * </pre>
     */
    GtwEventType_LocalCfgLoadFailed(1, 1),
    /**
     * <code>GtwEventType_APISvrRunFailed = 2;</code>
     *
     * <pre>
     *服务器启动失败
     * </pre>
     */
    GtwEventType_APISvrRunFailed(2, 2),
    /**
     * <code>GtwEventType_ForceUpdate = 3;</code>
     *
     * <pre>
     *客户端版本过低
     * </pre>
     */
    GtwEventType_ForceUpdate(3, 3),
    /**
     * <code>GtwEventType_LoginFailed = 4;</code>
     *
     * <pre>
     *登录失败
     * </pre>
     */
    GtwEventType_LoginFailed(4, 4),
    /**
     * <code>GtwEventType_UnAgreeDisclaimer = 5;</code>
     *
     * <pre>
     *未同意免责声明
     * </pre>
     */
    GtwEventType_UnAgreeDisclaimer(5, 5),
    /**
     * <code>GtwEventType_NetCfgMissing = 6;</code>
     *
     * <pre>
     *缺少必要网络配置信息;例如控制订阅额度
     * </pre>
     */
    GtwEventType_NetCfgMissing(6, 6),
    /**
     * <code>GtwEventType_KickedOut = 7;</code>
     *
     * <pre>
     *牛牛帐号在别处登录
     * </pre>
     */
    GtwEventType_KickedOut(7, 7),
    /**
     * <code>GtwEventType_LoginPwdChanged = 8;</code>
     *
     * <pre>
     *登录密码被修改
     * </pre>
     */
    GtwEventType_LoginPwdChanged(8, 8),
    /**
     * <code>GtwEventType_BanLogin = 9;</code>
     *
     * <pre>
     *用户被禁止登录
     * </pre>
     */
    GtwEventType_BanLogin(9, 9),
    /**
     * <code>GtwEventType_NeedPicVerifyCode = 10;</code>
     *
     * <pre>
     *需要图形验证码
     * </pre>
     */
    GtwEventType_NeedPicVerifyCode(10, 10),
    /**
     * <code>GtwEventType_NeedPhoneVerifyCode = 11;</code>
     *
     * <pre>
     *需要手机验证码
     * </pre>
     */
    GtwEventType_NeedPhoneVerifyCode(11, 11),
    /**
     * <code>GtwEventType_AppDataNotExist = 12;</code>
     *
     * <pre>
     *程序自带数据不存在
     * </pre>
     */
    GtwEventType_AppDataNotExist(12, 12),
    /**
     * <code>GtwEventType_NessaryDataMissing = 13;</code>
     *
     * <pre>
     *缺少必要数据
     * </pre>
     */
    GtwEventType_NessaryDataMissing(13, 13),
    /**
     * <code>GtwEventType_TradePwdChanged = 14;</code>
     *
     * <pre>
     *交易密码被修改
     * </pre>
     */
    GtwEventType_TradePwdChanged(14, 14),
    /**
     * <code>GtwEventType_EnableDeviceLock = 15;</code>
     *
     * <pre>
     *启用设备锁
     * </pre>
     */
    GtwEventType_EnableDeviceLock(15, 15),
    ;

    /**
     * <code>GtwEventType_None = 0;</code>
     *
     * <pre>
     *正常无错
     * </pre>
     */
    public static final int GtwEventType_None_VALUE = 0;
    /**
     * <code>GtwEventType_LocalCfgLoadFailed = 1;</code>
     *
     * <pre>
     *加载本地配置失败
     * </pre>
     */
    public static final int GtwEventType_LocalCfgLoadFailed_VALUE = 1;
    /**
     * <code>GtwEventType_APISvrRunFailed = 2;</code>
     *
     * <pre>
     *服务器启动失败
     * </pre>
     */
    public static final int GtwEventType_APISvrRunFailed_VALUE = 2;
    /**
     * <code>GtwEventType_ForceUpdate = 3;</code>
     *
     * <pre>
     *客户端版本过低
     * </pre>
     */
    public static final int GtwEventType_ForceUpdate_VALUE = 3;
    /**
     * <code>GtwEventType_LoginFailed = 4;</code>
     *
     * <pre>
     *登录失败
     * </pre>
     */
    public static final int GtwEventType_LoginFailed_VALUE = 4;
    /**
     * <code>GtwEventType_UnAgreeDisclaimer = 5;</code>
     *
     * <pre>
     *未同意免责声明
     * </pre>
     */
    public static final int GtwEventType_UnAgreeDisclaimer_VALUE = 5;
    /**
     * <code>GtwEventType_NetCfgMissing = 6;</code>
     *
     * <pre>
     *缺少必要网络配置信息;例如控制订阅额度
     * </pre>
     */
    public static final int GtwEventType_NetCfgMissing_VALUE = 6;
    /**
     * <code>GtwEventType_KickedOut = 7;</code>
     *
     * <pre>
     *牛牛帐号在别处登录
     * </pre>
     */
    public static final int GtwEventType_KickedOut_VALUE = 7;
    /**
     * <code>GtwEventType_LoginPwdChanged = 8;</code>
     *
     * <pre>
     *登录密码被修改
     * </pre>
     */
    public static final int GtwEventType_LoginPwdChanged_VALUE = 8;
    /**
     * <code>GtwEventType_BanLogin = 9;</code>
     *
     * <pre>
     *用户被禁止登录
     * </pre>
     */
    public static final int GtwEventType_BanLogin_VALUE = 9;
    /**
     * <code>GtwEventType_NeedPicVerifyCode = 10;</code>
     *
     * <pre>
     *需要图形验证码
     * </pre>
     */
    public static final int GtwEventType_NeedPicVerifyCode_VALUE = 10;
    /**
     * <code>GtwEventType_NeedPhoneVerifyCode = 11;</code>
     *
     * <pre>
     *需要手机验证码
     * </pre>
     */
    public static final int GtwEventType_NeedPhoneVerifyCode_VALUE = 11;
    /**
     * <code>GtwEventType_AppDataNotExist = 12;</code>
     *
     * <pre>
     *程序自带数据不存在
     * </pre>
     */
    public static final int GtwEventType_AppDataNotExist_VALUE = 12;
    /**
     * <code>GtwEventType_NessaryDataMissing = 13;</code>
     *
     * <pre>
     *缺少必要数据
     * </pre>
     */
    public static final int GtwEventType_NessaryDataMissing_VALUE = 13;
    /**
     * <code>GtwEventType_TradePwdChanged = 14;</code>
     *
     * <pre>
     *交易密码被修改
     * </pre>
     */
    public static final int GtwEventType_TradePwdChanged_VALUE = 14;
    /**
     * <code>GtwEventType_EnableDeviceLock = 15;</code>
     *
     * <pre>
     *启用设备锁
     * </pre>
     */
    public static final int GtwEventType_EnableDeviceLock_VALUE = 15;


    public final int getNumber() { return value; }

    public static GtwEventType valueOf(int value) {
      switch (value) {
        case 0: return GtwEventType_None;
        case 1: return GtwEventType_LocalCfgLoadFailed;
        case 2: return GtwEventType_APISvrRunFailed;
        case 3: return GtwEventType_ForceUpdate;
        case 4: return GtwEventType_LoginFailed;
        case 5: return GtwEventType_UnAgreeDisclaimer;
        case 6: return GtwEventType_NetCfgMissing;
        case 7: return GtwEventType_KickedOut;
        case 8: return GtwEventType_LoginPwdChanged;
        case 9: return GtwEventType_BanLogin;
        case 10: return GtwEventType_NeedPicVerifyCode;
        case 11: return GtwEventType_NeedPhoneVerifyCode;
        case 12: return GtwEventType_AppDataNotExist;
        case 13: return GtwEventType_NessaryDataMissing;
        case 14: return GtwEventType_TradePwdChanged;
        case 15: return GtwEventType_EnableDeviceLock;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GtwEventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GtwEventType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GtwEventType>() {
            public GtwEventType findValueByNumber(int number) {
              return GtwEventType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.futu.opend.api.protobuf.Notify.getDescriptor().getEnumTypes().get(1);
    }

    private static final GtwEventType[] VALUES = values();

    public static GtwEventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private GtwEventType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Notify.GtwEventType)
  }

  public interface GtwEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Notify.GtwEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 eventType = 1;</code>
     *
     * <pre>
     *GtwEventType,事件类型
     * </pre>
     */
    boolean hasEventType();
    /**
     * <code>required int32 eventType = 1;</code>
     *
     * <pre>
     *GtwEventType,事件类型
     * </pre>
     */
    int getEventType();

    /**
     * <code>required string desc = 2;</code>
     *
     * <pre>
     *事件描述
     * </pre>
     */
    boolean hasDesc();
    /**
     * <code>required string desc = 2;</code>
     *
     * <pre>
     *事件描述
     * </pre>
     */
    java.lang.String getDesc();
    /**
     * <code>required string desc = 2;</code>
     *
     * <pre>
     *事件描述
     * </pre>
     */
    com.google.protobuf.ByteString
        getDescBytes();
  }
  /**
   * Protobuf type {@code Notify.GtwEvent}
   */
  public static final class GtwEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Notify.GtwEvent)
      GtwEventOrBuilder {
    // Use GtwEvent.newBuilder() to construct.
    private GtwEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GtwEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GtwEvent defaultInstance;
    public static GtwEvent getDefaultInstance() {
      return defaultInstance;
    }

    public GtwEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GtwEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              eventType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              desc_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.opend.api.protobuf.Notify.internal_static_Notify_GtwEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.opend.api.protobuf.Notify.internal_static_Notify_GtwEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.opend.api.protobuf.Notify.GtwEvent.class, com.futu.opend.api.protobuf.Notify.GtwEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<GtwEvent> PARSER =
        new com.google.protobuf.AbstractParser<GtwEvent>() {
      public GtwEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GtwEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GtwEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int EVENTTYPE_FIELD_NUMBER = 1;
    private int eventType_;
    /**
     * <code>required int32 eventType = 1;</code>
     *
     * <pre>
     *GtwEventType,事件类型
     * </pre>
     */
    public boolean hasEventType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 eventType = 1;</code>
     *
     * <pre>
     *GtwEventType,事件类型
     * </pre>
     */
    public int getEventType() {
      return eventType_;
    }

    public static final int DESC_FIELD_NUMBER = 2;
    private java.lang.Object desc_;
    /**
     * <code>required string desc = 2;</code>
     *
     * <pre>
     *事件描述
     * </pre>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string desc = 2;</code>
     *
     * <pre>
     *事件描述
     * </pre>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string desc = 2;</code>
     *
     * <pre>
     *事件描述
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      eventType_ = 0;
      desc_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEventType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDesc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, eventType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDescBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, eventType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDescBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.futu.opend.api.protobuf.Notify.GtwEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.Notify.GtwEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.Notify.GtwEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.Notify.GtwEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.Notify.GtwEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.Notify.GtwEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.Notify.GtwEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.futu.opend.api.protobuf.Notify.GtwEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.Notify.GtwEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.Notify.GtwEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.futu.opend.api.protobuf.Notify.GtwEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Notify.GtwEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Notify.GtwEvent)
        com.futu.opend.api.protobuf.Notify.GtwEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.opend.api.protobuf.Notify.internal_static_Notify_GtwEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.opend.api.protobuf.Notify.internal_static_Notify_GtwEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.opend.api.protobuf.Notify.GtwEvent.class, com.futu.opend.api.protobuf.Notify.GtwEvent.Builder.class);
      }

      // Construct using com.futu.opend.api.protobuf.Notify.GtwEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        eventType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.opend.api.protobuf.Notify.internal_static_Notify_GtwEvent_descriptor;
      }

      public com.futu.opend.api.protobuf.Notify.GtwEvent getDefaultInstanceForType() {
        return com.futu.opend.api.protobuf.Notify.GtwEvent.getDefaultInstance();
      }

      public com.futu.opend.api.protobuf.Notify.GtwEvent build() {
        com.futu.opend.api.protobuf.Notify.GtwEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.opend.api.protobuf.Notify.GtwEvent buildPartial() {
        com.futu.opend.api.protobuf.Notify.GtwEvent result = new com.futu.opend.api.protobuf.Notify.GtwEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.eventType_ = eventType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.desc_ = desc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.opend.api.protobuf.Notify.GtwEvent) {
          return mergeFrom((com.futu.opend.api.protobuf.Notify.GtwEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.opend.api.protobuf.Notify.GtwEvent other) {
        if (other == com.futu.opend.api.protobuf.Notify.GtwEvent.getDefaultInstance()) return this;
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000002;
          desc_ = other.desc_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEventType()) {
          
          return false;
        }
        if (!hasDesc()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.opend.api.protobuf.Notify.GtwEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.opend.api.protobuf.Notify.GtwEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int eventType_ ;
      /**
       * <code>required int32 eventType = 1;</code>
       *
       * <pre>
       *GtwEventType,事件类型
       * </pre>
       */
      public boolean hasEventType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 eventType = 1;</code>
       *
       * <pre>
       *GtwEventType,事件类型
       * </pre>
       */
      public int getEventType() {
        return eventType_;
      }
      /**
       * <code>required int32 eventType = 1;</code>
       *
       * <pre>
       *GtwEventType,事件类型
       * </pre>
       */
      public Builder setEventType(int value) {
        bitField0_ |= 0x00000001;
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 eventType = 1;</code>
       *
       * <pre>
       *GtwEventType,事件类型
       * </pre>
       */
      public Builder clearEventType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eventType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>required string desc = 2;</code>
       *
       * <pre>
       *事件描述
       * </pre>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string desc = 2;</code>
       *
       * <pre>
       *事件描述
       * </pre>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            desc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string desc = 2;</code>
       *
       * <pre>
       *事件描述
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string desc = 2;</code>
       *
       * <pre>
       *事件描述
       * </pre>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 2;</code>
       *
       * <pre>
       *事件描述
       * </pre>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 2;</code>
       *
       * <pre>
       *事件描述
       * </pre>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        desc_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Notify.GtwEvent)
    }

    static {
      defaultInstance = new GtwEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Notify.GtwEvent)
  }

  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Notify.S2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *通知类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *通知类型
     * </pre>
     */
    int getType();

    /**
     * <code>optional .Notify.GtwEvent event = 2;</code>
     *
     * <pre>
     *事件通息
     * </pre>
     */
    boolean hasEvent();
    /**
     * <code>optional .Notify.GtwEvent event = 2;</code>
     *
     * <pre>
     *事件通息
     * </pre>
     */
    com.futu.opend.api.protobuf.Notify.GtwEvent getEvent();
    /**
     * <code>optional .Notify.GtwEvent event = 2;</code>
     *
     * <pre>
     *事件通息
     * </pre>
     */
    com.futu.opend.api.protobuf.Notify.GtwEventOrBuilder getEventOrBuilder();
  }
  /**
   * Protobuf type {@code Notify.S2C}
   */
  public static final class S2C extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Notify.S2C)
      S2COrBuilder {
    // Use S2C.newBuilder() to construct.
    private S2C(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private S2C(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final S2C defaultInstance;
    public static S2C getDefaultInstance() {
      return defaultInstance;
    }

    public S2C getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 18: {
              com.futu.opend.api.protobuf.Notify.GtwEvent.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = event_.toBuilder();
              }
              event_ = input.readMessage(com.futu.opend.api.protobuf.Notify.GtwEvent.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(event_);
                event_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.opend.api.protobuf.Notify.internal_static_Notify_S2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.opend.api.protobuf.Notify.internal_static_Notify_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.opend.api.protobuf.Notify.S2C.class, com.futu.opend.api.protobuf.Notify.S2C.Builder.class);
    }

    public static com.google.protobuf.Parser<S2C> PARSER =
        new com.google.protobuf.AbstractParser<S2C>() {
      public S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<S2C> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *通知类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *通知类型
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int EVENT_FIELD_NUMBER = 2;
    private com.futu.opend.api.protobuf.Notify.GtwEvent event_;
    /**
     * <code>optional .Notify.GtwEvent event = 2;</code>
     *
     * <pre>
     *事件通息
     * </pre>
     */
    public boolean hasEvent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Notify.GtwEvent event = 2;</code>
     *
     * <pre>
     *事件通息
     * </pre>
     */
    public com.futu.opend.api.protobuf.Notify.GtwEvent getEvent() {
      return event_;
    }
    /**
     * <code>optional .Notify.GtwEvent event = 2;</code>
     *
     * <pre>
     *事件通息
     * </pre>
     */
    public com.futu.opend.api.protobuf.Notify.GtwEventOrBuilder getEventOrBuilder() {
      return event_;
    }

    private void initFields() {
      type_ = 0;
      event_ = com.futu.opend.api.protobuf.Notify.GtwEvent.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasEvent()) {
        if (!getEvent().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, event_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, event_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.futu.opend.api.protobuf.Notify.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.Notify.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.Notify.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.Notify.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.Notify.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.Notify.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.Notify.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.futu.opend.api.protobuf.Notify.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.Notify.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.Notify.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.futu.opend.api.protobuf.Notify.S2C prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Notify.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Notify.S2C)
        com.futu.opend.api.protobuf.Notify.S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.opend.api.protobuf.Notify.internal_static_Notify_S2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.opend.api.protobuf.Notify.internal_static_Notify_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.opend.api.protobuf.Notify.S2C.class, com.futu.opend.api.protobuf.Notify.S2C.Builder.class);
      }

      // Construct using com.futu.opend.api.protobuf.Notify.S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEventFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (eventBuilder_ == null) {
          event_ = com.futu.opend.api.protobuf.Notify.GtwEvent.getDefaultInstance();
        } else {
          eventBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.opend.api.protobuf.Notify.internal_static_Notify_S2C_descriptor;
      }

      public com.futu.opend.api.protobuf.Notify.S2C getDefaultInstanceForType() {
        return com.futu.opend.api.protobuf.Notify.S2C.getDefaultInstance();
      }

      public com.futu.opend.api.protobuf.Notify.S2C build() {
        com.futu.opend.api.protobuf.Notify.S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.opend.api.protobuf.Notify.S2C buildPartial() {
        com.futu.opend.api.protobuf.Notify.S2C result = new com.futu.opend.api.protobuf.Notify.S2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (eventBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = eventBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.opend.api.protobuf.Notify.S2C) {
          return mergeFrom((com.futu.opend.api.protobuf.Notify.S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.opend.api.protobuf.Notify.S2C other) {
        if (other == com.futu.opend.api.protobuf.Notify.S2C.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasEvent()) {
          mergeEvent(other.getEvent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasEvent()) {
          if (!getEvent().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.opend.api.protobuf.Notify.S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.opend.api.protobuf.Notify.S2C) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *通知类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *通知类型
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *通知类型
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *通知类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.futu.opend.api.protobuf.Notify.GtwEvent event_ = com.futu.opend.api.protobuf.Notify.GtwEvent.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.Notify.GtwEvent, com.futu.opend.api.protobuf.Notify.GtwEvent.Builder, com.futu.opend.api.protobuf.Notify.GtwEventOrBuilder> eventBuilder_;
      /**
       * <code>optional .Notify.GtwEvent event = 2;</code>
       *
       * <pre>
       *事件通息
       * </pre>
       */
      public boolean hasEvent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Notify.GtwEvent event = 2;</code>
       *
       * <pre>
       *事件通息
       * </pre>
       */
      public com.futu.opend.api.protobuf.Notify.GtwEvent getEvent() {
        if (eventBuilder_ == null) {
          return event_;
        } else {
          return eventBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Notify.GtwEvent event = 2;</code>
       *
       * <pre>
       *事件通息
       * </pre>
       */
      public Builder setEvent(com.futu.opend.api.protobuf.Notify.GtwEvent value) {
        if (eventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          eventBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Notify.GtwEvent event = 2;</code>
       *
       * <pre>
       *事件通息
       * </pre>
       */
      public Builder setEvent(
          com.futu.opend.api.protobuf.Notify.GtwEvent.Builder builderForValue) {
        if (eventBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          eventBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Notify.GtwEvent event = 2;</code>
       *
       * <pre>
       *事件通息
       * </pre>
       */
      public Builder mergeEvent(com.futu.opend.api.protobuf.Notify.GtwEvent value) {
        if (eventBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              event_ != com.futu.opend.api.protobuf.Notify.GtwEvent.getDefaultInstance()) {
            event_ =
              com.futu.opend.api.protobuf.Notify.GtwEvent.newBuilder(event_).mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          eventBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Notify.GtwEvent event = 2;</code>
       *
       * <pre>
       *事件通息
       * </pre>
       */
      public Builder clearEvent() {
        if (eventBuilder_ == null) {
          event_ = com.futu.opend.api.protobuf.Notify.GtwEvent.getDefaultInstance();
          onChanged();
        } else {
          eventBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Notify.GtwEvent event = 2;</code>
       *
       * <pre>
       *事件通息
       * </pre>
       */
      public com.futu.opend.api.protobuf.Notify.GtwEvent.Builder getEventBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getEventFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Notify.GtwEvent event = 2;</code>
       *
       * <pre>
       *事件通息
       * </pre>
       */
      public com.futu.opend.api.protobuf.Notify.GtwEventOrBuilder getEventOrBuilder() {
        if (eventBuilder_ != null) {
          return eventBuilder_.getMessageOrBuilder();
        } else {
          return event_;
        }
      }
      /**
       * <code>optional .Notify.GtwEvent event = 2;</code>
       *
       * <pre>
       *事件通息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.Notify.GtwEvent, com.futu.opend.api.protobuf.Notify.GtwEvent.Builder, com.futu.opend.api.protobuf.Notify.GtwEventOrBuilder> 
          getEventFieldBuilder() {
        if (eventBuilder_ == null) {
          eventBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.futu.opend.api.protobuf.Notify.GtwEvent, com.futu.opend.api.protobuf.Notify.GtwEvent.Builder, com.futu.opend.api.protobuf.Notify.GtwEventOrBuilder>(
                  getEvent(),
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        return eventBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Notify.S2C)
    }

    static {
      defaultInstance = new S2C(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Notify.S2C)
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Notify.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *RetType,返回结果
     * </pre>
     */
    boolean hasRetType();
    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *RetType,返回结果
     * </pre>
     */
    int getRetType();

    /**
     * <code>optional string retMsg = 2;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();

    /**
     * <code>optional int32 errCode = 3;</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    int getErrCode();

    /**
     * <code>optional .Notify.S2C s2c = 4;</code>
     */
    boolean hasS2C();
    /**
     * <code>optional .Notify.S2C s2c = 4;</code>
     */
    com.futu.opend.api.protobuf.Notify.S2C getS2C();
    /**
     * <code>optional .Notify.S2C s2c = 4;</code>
     */
    com.futu.opend.api.protobuf.Notify.S2COrBuilder getS2COrBuilder();
  }
  /**
   * Protobuf type {@code Notify.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Notify.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              retType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              retMsg_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errCode_ = input.readInt32();
              break;
            }
            case 34: {
              com.futu.opend.api.protobuf.Notify.S2C.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = s2C_.toBuilder();
              }
              s2C_ = input.readMessage(com.futu.opend.api.protobuf.Notify.S2C.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2C_);
                s2C_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.opend.api.protobuf.Notify.internal_static_Notify_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.opend.api.protobuf.Notify.internal_static_Notify_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.opend.api.protobuf.Notify.Response.class, com.futu.opend.api.protobuf.Notify.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RETTYPE_FIELD_NUMBER = 1;
    private int retType_;
    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *RetType,返回结果
     * </pre>
     */
    public boolean hasRetType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *RetType,返回结果
     * </pre>
     */
    public int getRetType() {
      return retType_;
    }

    public static final int RETMSG_FIELD_NUMBER = 2;
    private java.lang.Object retMsg_;
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int S2C_FIELD_NUMBER = 4;
    private com.futu.opend.api.protobuf.Notify.S2C s2C_;
    /**
     * <code>optional .Notify.S2C s2c = 4;</code>
     */
    public boolean hasS2C() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Notify.S2C s2c = 4;</code>
     */
    public com.futu.opend.api.protobuf.Notify.S2C getS2C() {
      return s2C_;
    }
    /**
     * <code>optional .Notify.S2C s2c = 4;</code>
     */
    public com.futu.opend.api.protobuf.Notify.S2COrBuilder getS2COrBuilder() {
      return s2C_;
    }

    private void initFields() {
      retType_ = -400;
      retMsg_ = "";
      errCode_ = 0;
      s2C_ = com.futu.opend.api.protobuf.Notify.S2C.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRetType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasS2C()) {
        if (!getS2C().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, retType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRetMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, s2C_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRetMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, s2C_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.futu.opend.api.protobuf.Notify.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.Notify.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.Notify.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.Notify.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.Notify.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.Notify.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.Notify.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.futu.opend.api.protobuf.Notify.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.Notify.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.Notify.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.futu.opend.api.protobuf.Notify.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Notify.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Notify.Response)
        com.futu.opend.api.protobuf.Notify.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.opend.api.protobuf.Notify.internal_static_Notify_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.opend.api.protobuf.Notify.internal_static_Notify_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.opend.api.protobuf.Notify.Response.class, com.futu.opend.api.protobuf.Notify.Response.Builder.class);
      }

      // Construct using com.futu.opend.api.protobuf.Notify.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getS2CFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        retType_ = -400;
        bitField0_ = (bitField0_ & ~0x00000001);
        retMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (s2CBuilder_ == null) {
          s2C_ = com.futu.opend.api.protobuf.Notify.S2C.getDefaultInstance();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.opend.api.protobuf.Notify.internal_static_Notify_Response_descriptor;
      }

      public com.futu.opend.api.protobuf.Notify.Response getDefaultInstanceForType() {
        return com.futu.opend.api.protobuf.Notify.Response.getDefaultInstance();
      }

      public com.futu.opend.api.protobuf.Notify.Response build() {
        com.futu.opend.api.protobuf.Notify.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.opend.api.protobuf.Notify.Response buildPartial() {
        com.futu.opend.api.protobuf.Notify.Response result = new com.futu.opend.api.protobuf.Notify.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retType_ = retType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.retMsg_ = retMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (s2CBuilder_ == null) {
          result.s2C_ = s2C_;
        } else {
          result.s2C_ = s2CBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.opend.api.protobuf.Notify.Response) {
          return mergeFrom((com.futu.opend.api.protobuf.Notify.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.opend.api.protobuf.Notify.Response other) {
        if (other == com.futu.opend.api.protobuf.Notify.Response.getDefaultInstance()) return this;
        if (other.hasRetType()) {
          setRetType(other.getRetType());
        }
        if (other.hasRetMsg()) {
          bitField0_ |= 0x00000002;
          retMsg_ = other.retMsg_;
          onChanged();
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasS2C()) {
          mergeS2C(other.getS2C());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRetType()) {
          
          return false;
        }
        if (hasS2C()) {
          if (!getS2C().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.opend.api.protobuf.Notify.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.opend.api.protobuf.Notify.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int retType_ = -400;
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *RetType,返回结果
       * </pre>
       */
      public boolean hasRetType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *RetType,返回结果
       * </pre>
       */
      public int getRetType() {
        return retType_;
      }
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *RetType,返回结果
       * </pre>
       */
      public Builder setRetType(int value) {
        bitField0_ |= 0x00000001;
        retType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *RetType,返回结果
       * </pre>
       */
      public Builder clearRetType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retType_ = -400;
        onChanged();
        return this;
      }

      private java.lang.Object retMsg_ = "";
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public boolean hasRetMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public java.lang.String getRetMsg() {
        java.lang.Object ref = retMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            retMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        java.lang.Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder clearRetMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retMsg_ = getDefaultInstance().getRetMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000004;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private com.futu.opend.api.protobuf.Notify.S2C s2C_ = com.futu.opend.api.protobuf.Notify.S2C.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.Notify.S2C, com.futu.opend.api.protobuf.Notify.S2C.Builder, com.futu.opend.api.protobuf.Notify.S2COrBuilder> s2CBuilder_;
      /**
       * <code>optional .Notify.S2C s2c = 4;</code>
       */
      public boolean hasS2C() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Notify.S2C s2c = 4;</code>
       */
      public com.futu.opend.api.protobuf.Notify.S2C getS2C() {
        if (s2CBuilder_ == null) {
          return s2C_;
        } else {
          return s2CBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Notify.S2C s2c = 4;</code>
       */
      public Builder setS2C(com.futu.opend.api.protobuf.Notify.S2C value) {
        if (s2CBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2C_ = value;
          onChanged();
        } else {
          s2CBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Notify.S2C s2c = 4;</code>
       */
      public Builder setS2C(
          com.futu.opend.api.protobuf.Notify.S2C.Builder builderForValue) {
        if (s2CBuilder_ == null) {
          s2C_ = builderForValue.build();
          onChanged();
        } else {
          s2CBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Notify.S2C s2c = 4;</code>
       */
      public Builder mergeS2C(com.futu.opend.api.protobuf.Notify.S2C value) {
        if (s2CBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              s2C_ != com.futu.opend.api.protobuf.Notify.S2C.getDefaultInstance()) {
            s2C_ =
              com.futu.opend.api.protobuf.Notify.S2C.newBuilder(s2C_).mergeFrom(value).buildPartial();
          } else {
            s2C_ = value;
          }
          onChanged();
        } else {
          s2CBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Notify.S2C s2c = 4;</code>
       */
      public Builder clearS2C() {
        if (s2CBuilder_ == null) {
          s2C_ = com.futu.opend.api.protobuf.Notify.S2C.getDefaultInstance();
          onChanged();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Notify.S2C s2c = 4;</code>
       */
      public com.futu.opend.api.protobuf.Notify.S2C.Builder getS2CBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getS2CFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Notify.S2C s2c = 4;</code>
       */
      public com.futu.opend.api.protobuf.Notify.S2COrBuilder getS2COrBuilder() {
        if (s2CBuilder_ != null) {
          return s2CBuilder_.getMessageOrBuilder();
        } else {
          return s2C_;
        }
      }
      /**
       * <code>optional .Notify.S2C s2c = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.Notify.S2C, com.futu.opend.api.protobuf.Notify.S2C.Builder, com.futu.opend.api.protobuf.Notify.S2COrBuilder> 
          getS2CFieldBuilder() {
        if (s2CBuilder_ == null) {
          s2CBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.futu.opend.api.protobuf.Notify.S2C, com.futu.opend.api.protobuf.Notify.S2C.Builder, com.futu.opend.api.protobuf.Notify.S2COrBuilder>(
                  getS2C(),
                  getParentForChildren(),
                  isClean());
          s2C_ = null;
        }
        return s2CBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Notify.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Notify.Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Notify_GtwEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Notify_GtwEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Notify_S2C_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Notify_S2C_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Notify_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Notify_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Notify.proto\022\006Notify\032\014Common.proto\"+\n\010" +
      "GtwEvent\022\021\n\teventType\030\001 \002(\005\022\014\n\004desc\030\002 \002(" +
      "\t\"4\n\003S2C\022\014\n\004type\030\001 \002(\005\022\037\n\005event\030\002 \001(\0132\020." +
      "Notify.GtwEvent\"\\\n\010Response\022\025\n\007retType\030\001" +
      " \002(\005:\004-400\022\016\n\006retMsg\030\002 \001(\t\022\017\n\007errCode\030\003 " +
      "\001(\005\022\030\n\003s2c\030\004 \001(\0132\013.Notify.S2C*:\n\nNotifyT" +
      "ype\022\023\n\017NotifyType_None\020\000\022\027\n\023NotifyType_G" +
      "twEvent\020\001*\233\004\n\014GtwEventType\022\025\n\021GtwEventTy" +
      "pe_None\020\000\022#\n\037GtwEventType_LocalCfgLoadFa" +
      "iled\020\001\022 \n\034GtwEventType_APISvrRunFailed\020\002",
      "\022\034\n\030GtwEventType_ForceUpdate\020\003\022\034\n\030GtwEve" +
      "ntType_LoginFailed\020\004\022\"\n\036GtwEventType_UnA" +
      "greeDisclaimer\020\005\022\036\n\032GtwEventType_NetCfgM" +
      "issing\020\006\022\032\n\026GtwEventType_KickedOut\020\007\022 \n\034" +
      "GtwEventType_LoginPwdChanged\020\010\022\031\n\025GtwEve" +
      "ntType_BanLogin\020\t\022\"\n\036GtwEventType_NeedPi" +
      "cVerifyCode\020\n\022$\n GtwEventType_NeedPhoneV" +
      "erifyCode\020\013\022 \n\034GtwEventType_AppDataNotEx" +
      "ist\020\014\022#\n\037GtwEventType_NessaryDataMissing" +
      "\020\r\022 \n\034GtwEventType_TradePwdChanged\020\016\022!\n\035",
      "GtwEventType_EnableDeviceLock\020\017B\035\n\033com.f" +
      "utu.opend.api.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.futu.opend.api.protobuf.Common.getDescriptor(),
        }, assigner);
    internal_static_Notify_GtwEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Notify_GtwEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Notify_GtwEvent_descriptor,
        new java.lang.String[] { "EventType", "Desc", });
    internal_static_Notify_S2C_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Notify_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Notify_S2C_descriptor,
        new java.lang.String[] { "Type", "Event", });
    internal_static_Notify_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Notify_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Notify_Response_descriptor,
        new java.lang.String[] { "RetType", "RetMsg", "ErrCode", "S2C", });
    com.futu.opend.api.protobuf.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
