// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Qot_UpdateBasicQot.proto

package com.futu.opend.api.protobuf;

public final class QotUpdateBasicQot {
  private QotUpdateBasicQot() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdateBasicQot.S2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     *
     * <pre>
     *股票基本行情
     * </pre>
     */
    java.util.List<com.futu.opend.api.protobuf.QotCommon.BasicQot> 
        getBasicQotListList();
    /**
     * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     *
     * <pre>
     *股票基本行情
     * </pre>
     */
    com.futu.opend.api.protobuf.QotCommon.BasicQot getBasicQotList(int index);
    /**
     * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     *
     * <pre>
     *股票基本行情
     * </pre>
     */
    int getBasicQotListCount();
    /**
     * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     *
     * <pre>
     *股票基本行情
     * </pre>
     */
    java.util.List<? extends com.futu.opend.api.protobuf.QotCommon.BasicQotOrBuilder> 
        getBasicQotListOrBuilderList();
    /**
     * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     *
     * <pre>
     *股票基本行情
     * </pre>
     */
    com.futu.opend.api.protobuf.QotCommon.BasicQotOrBuilder getBasicQotListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Qot_UpdateBasicQot.S2C}
   */
  public static final class S2C extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Qot_UpdateBasicQot.S2C)
      S2COrBuilder {
    // Use S2C.newBuilder() to construct.
    private S2C(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private S2C(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final S2C defaultInstance;
    public static S2C getDefaultInstance() {
      return defaultInstance;
    }

    public S2C getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                basicQotList_ = new java.util.ArrayList<com.futu.opend.api.protobuf.QotCommon.BasicQot>();
                mutable_bitField0_ |= 0x00000001;
              }
              basicQotList_.add(input.readMessage(com.futu.opend.api.protobuf.QotCommon.BasicQot.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          basicQotList_ = java.util.Collections.unmodifiableList(basicQotList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.opend.api.protobuf.QotUpdateBasicQot.internal_static_Qot_UpdateBasicQot_S2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.opend.api.protobuf.QotUpdateBasicQot.internal_static_Qot_UpdateBasicQot_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.class, com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.Builder.class);
    }

    public static com.google.protobuf.Parser<S2C> PARSER =
        new com.google.protobuf.AbstractParser<S2C>() {
      public S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<S2C> getParserForType() {
      return PARSER;
    }

    public static final int BASICQOTLIST_FIELD_NUMBER = 1;
    private java.util.List<com.futu.opend.api.protobuf.QotCommon.BasicQot> basicQotList_;
    /**
     * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     *
     * <pre>
     *股票基本行情
     * </pre>
     */
    public java.util.List<com.futu.opend.api.protobuf.QotCommon.BasicQot> getBasicQotListList() {
      return basicQotList_;
    }
    /**
     * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     *
     * <pre>
     *股票基本行情
     * </pre>
     */
    public java.util.List<? extends com.futu.opend.api.protobuf.QotCommon.BasicQotOrBuilder> 
        getBasicQotListOrBuilderList() {
      return basicQotList_;
    }
    /**
     * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     *
     * <pre>
     *股票基本行情
     * </pre>
     */
    public int getBasicQotListCount() {
      return basicQotList_.size();
    }
    /**
     * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     *
     * <pre>
     *股票基本行情
     * </pre>
     */
    public com.futu.opend.api.protobuf.QotCommon.BasicQot getBasicQotList(int index) {
      return basicQotList_.get(index);
    }
    /**
     * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     *
     * <pre>
     *股票基本行情
     * </pre>
     */
    public com.futu.opend.api.protobuf.QotCommon.BasicQotOrBuilder getBasicQotListOrBuilder(
        int index) {
      return basicQotList_.get(index);
    }

    private void initFields() {
      basicQotList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getBasicQotListCount(); i++) {
        if (!getBasicQotList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < basicQotList_.size(); i++) {
        output.writeMessage(1, basicQotList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < basicQotList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, basicQotList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdateBasicQot.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdateBasicQot.S2C)
        com.futu.opend.api.protobuf.QotUpdateBasicQot.S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.opend.api.protobuf.QotUpdateBasicQot.internal_static_Qot_UpdateBasicQot_S2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.opend.api.protobuf.QotUpdateBasicQot.internal_static_Qot_UpdateBasicQot_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.class, com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.Builder.class);
      }

      // Construct using com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBasicQotListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (basicQotListBuilder_ == null) {
          basicQotList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          basicQotListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.opend.api.protobuf.QotUpdateBasicQot.internal_static_Qot_UpdateBasicQot_S2C_descriptor;
      }

      public com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C getDefaultInstanceForType() {
        return com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.getDefaultInstance();
      }

      public com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C build() {
        com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C buildPartial() {
        com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C result = new com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C(this);
        int from_bitField0_ = bitField0_;
        if (basicQotListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            basicQotList_ = java.util.Collections.unmodifiableList(basicQotList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.basicQotList_ = basicQotList_;
        } else {
          result.basicQotList_ = basicQotListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C) {
          return mergeFrom((com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C other) {
        if (other == com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.getDefaultInstance()) return this;
        if (basicQotListBuilder_ == null) {
          if (!other.basicQotList_.isEmpty()) {
            if (basicQotList_.isEmpty()) {
              basicQotList_ = other.basicQotList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBasicQotListIsMutable();
              basicQotList_.addAll(other.basicQotList_);
            }
            onChanged();
          }
        } else {
          if (!other.basicQotList_.isEmpty()) {
            if (basicQotListBuilder_.isEmpty()) {
              basicQotListBuilder_.dispose();
              basicQotListBuilder_ = null;
              basicQotList_ = other.basicQotList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              basicQotListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBasicQotListFieldBuilder() : null;
            } else {
              basicQotListBuilder_.addAllMessages(other.basicQotList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getBasicQotListCount(); i++) {
          if (!getBasicQotList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.futu.opend.api.protobuf.QotCommon.BasicQot> basicQotList_ =
        java.util.Collections.emptyList();
      private void ensureBasicQotListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          basicQotList_ = new java.util.ArrayList<com.futu.opend.api.protobuf.QotCommon.BasicQot>(basicQotList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.futu.opend.api.protobuf.QotCommon.BasicQot, com.futu.opend.api.protobuf.QotCommon.BasicQot.Builder, com.futu.opend.api.protobuf.QotCommon.BasicQotOrBuilder> basicQotListBuilder_;

      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public java.util.List<com.futu.opend.api.protobuf.QotCommon.BasicQot> getBasicQotListList() {
        if (basicQotListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(basicQotList_);
        } else {
          return basicQotListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public int getBasicQotListCount() {
        if (basicQotListBuilder_ == null) {
          return basicQotList_.size();
        } else {
          return basicQotListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.BasicQot getBasicQotList(int index) {
        if (basicQotListBuilder_ == null) {
          return basicQotList_.get(index);
        } else {
          return basicQotListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public Builder setBasicQotList(
          int index, com.futu.opend.api.protobuf.QotCommon.BasicQot value) {
        if (basicQotListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBasicQotListIsMutable();
          basicQotList_.set(index, value);
          onChanged();
        } else {
          basicQotListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public Builder setBasicQotList(
          int index, com.futu.opend.api.protobuf.QotCommon.BasicQot.Builder builderForValue) {
        if (basicQotListBuilder_ == null) {
          ensureBasicQotListIsMutable();
          basicQotList_.set(index, builderForValue.build());
          onChanged();
        } else {
          basicQotListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public Builder addBasicQotList(com.futu.opend.api.protobuf.QotCommon.BasicQot value) {
        if (basicQotListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBasicQotListIsMutable();
          basicQotList_.add(value);
          onChanged();
        } else {
          basicQotListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public Builder addBasicQotList(
          int index, com.futu.opend.api.protobuf.QotCommon.BasicQot value) {
        if (basicQotListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBasicQotListIsMutable();
          basicQotList_.add(index, value);
          onChanged();
        } else {
          basicQotListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public Builder addBasicQotList(
          com.futu.opend.api.protobuf.QotCommon.BasicQot.Builder builderForValue) {
        if (basicQotListBuilder_ == null) {
          ensureBasicQotListIsMutable();
          basicQotList_.add(builderForValue.build());
          onChanged();
        } else {
          basicQotListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public Builder addBasicQotList(
          int index, com.futu.opend.api.protobuf.QotCommon.BasicQot.Builder builderForValue) {
        if (basicQotListBuilder_ == null) {
          ensureBasicQotListIsMutable();
          basicQotList_.add(index, builderForValue.build());
          onChanged();
        } else {
          basicQotListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public Builder addAllBasicQotList(
          java.lang.Iterable<? extends com.futu.opend.api.protobuf.QotCommon.BasicQot> values) {
        if (basicQotListBuilder_ == null) {
          ensureBasicQotListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, basicQotList_);
          onChanged();
        } else {
          basicQotListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public Builder clearBasicQotList() {
        if (basicQotListBuilder_ == null) {
          basicQotList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          basicQotListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public Builder removeBasicQotList(int index) {
        if (basicQotListBuilder_ == null) {
          ensureBasicQotListIsMutable();
          basicQotList_.remove(index);
          onChanged();
        } else {
          basicQotListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.BasicQot.Builder getBasicQotListBuilder(
          int index) {
        return getBasicQotListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.BasicQotOrBuilder getBasicQotListOrBuilder(
          int index) {
        if (basicQotListBuilder_ == null) {
          return basicQotList_.get(index);  } else {
          return basicQotListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public java.util.List<? extends com.futu.opend.api.protobuf.QotCommon.BasicQotOrBuilder> 
           getBasicQotListOrBuilderList() {
        if (basicQotListBuilder_ != null) {
          return basicQotListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(basicQotList_);
        }
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.BasicQot.Builder addBasicQotListBuilder() {
        return getBasicQotListFieldBuilder().addBuilder(
            com.futu.opend.api.protobuf.QotCommon.BasicQot.getDefaultInstance());
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.BasicQot.Builder addBasicQotListBuilder(
          int index) {
        return getBasicQotListFieldBuilder().addBuilder(
            index, com.futu.opend.api.protobuf.QotCommon.BasicQot.getDefaultInstance());
      }
      /**
       * <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
       *
       * <pre>
       *股票基本行情
       * </pre>
       */
      public java.util.List<com.futu.opend.api.protobuf.QotCommon.BasicQot.Builder> 
           getBasicQotListBuilderList() {
        return getBasicQotListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.futu.opend.api.protobuf.QotCommon.BasicQot, com.futu.opend.api.protobuf.QotCommon.BasicQot.Builder, com.futu.opend.api.protobuf.QotCommon.BasicQotOrBuilder> 
          getBasicQotListFieldBuilder() {
        if (basicQotListBuilder_ == null) {
          basicQotListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.futu.opend.api.protobuf.QotCommon.BasicQot, com.futu.opend.api.protobuf.QotCommon.BasicQot.Builder, com.futu.opend.api.protobuf.QotCommon.BasicQotOrBuilder>(
                  basicQotList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          basicQotList_ = null;
        }
        return basicQotListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Qot_UpdateBasicQot.S2C)
    }

    static {
      defaultInstance = new S2C(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdateBasicQot.S2C)
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdateBasicQot.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *RetType,返回结果
     * </pre>
     */
    boolean hasRetType();
    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *RetType,返回结果
     * </pre>
     */
    int getRetType();

    /**
     * <code>optional string retMsg = 2;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();

    /**
     * <code>optional int32 errCode = 3;</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    int getErrCode();

    /**
     * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
     */
    boolean hasS2C();
    /**
     * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
     */
    com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C getS2C();
    /**
     * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
     */
    com.futu.opend.api.protobuf.QotUpdateBasicQot.S2COrBuilder getS2COrBuilder();
  }
  /**
   * Protobuf type {@code Qot_UpdateBasicQot.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Qot_UpdateBasicQot.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              retType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              retMsg_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errCode_ = input.readInt32();
              break;
            }
            case 34: {
              com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = s2C_.toBuilder();
              }
              s2C_ = input.readMessage(com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2C_);
                s2C_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.opend.api.protobuf.QotUpdateBasicQot.internal_static_Qot_UpdateBasicQot_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.opend.api.protobuf.QotUpdateBasicQot.internal_static_Qot_UpdateBasicQot_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.opend.api.protobuf.QotUpdateBasicQot.Response.class, com.futu.opend.api.protobuf.QotUpdateBasicQot.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RETTYPE_FIELD_NUMBER = 1;
    private int retType_;
    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *RetType,返回结果
     * </pre>
     */
    public boolean hasRetType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *RetType,返回结果
     * </pre>
     */
    public int getRetType() {
      return retType_;
    }

    public static final int RETMSG_FIELD_NUMBER = 2;
    private java.lang.Object retMsg_;
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int S2C_FIELD_NUMBER = 4;
    private com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C s2C_;
    /**
     * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
     */
    public boolean hasS2C() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
     */
    public com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C getS2C() {
      return s2C_;
    }
    /**
     * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
     */
    public com.futu.opend.api.protobuf.QotUpdateBasicQot.S2COrBuilder getS2COrBuilder() {
      return s2C_;
    }

    private void initFields() {
      retType_ = -400;
      retMsg_ = "";
      errCode_ = 0;
      s2C_ = com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRetType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasS2C()) {
        if (!getS2C().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, retType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRetMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, s2C_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRetMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, s2C_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.QotUpdateBasicQot.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.futu.opend.api.protobuf.QotUpdateBasicQot.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdateBasicQot.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdateBasicQot.Response)
        com.futu.opend.api.protobuf.QotUpdateBasicQot.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.opend.api.protobuf.QotUpdateBasicQot.internal_static_Qot_UpdateBasicQot_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.opend.api.protobuf.QotUpdateBasicQot.internal_static_Qot_UpdateBasicQot_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.opend.api.protobuf.QotUpdateBasicQot.Response.class, com.futu.opend.api.protobuf.QotUpdateBasicQot.Response.Builder.class);
      }

      // Construct using com.futu.opend.api.protobuf.QotUpdateBasicQot.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getS2CFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        retType_ = -400;
        bitField0_ = (bitField0_ & ~0x00000001);
        retMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (s2CBuilder_ == null) {
          s2C_ = com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.getDefaultInstance();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.opend.api.protobuf.QotUpdateBasicQot.internal_static_Qot_UpdateBasicQot_Response_descriptor;
      }

      public com.futu.opend.api.protobuf.QotUpdateBasicQot.Response getDefaultInstanceForType() {
        return com.futu.opend.api.protobuf.QotUpdateBasicQot.Response.getDefaultInstance();
      }

      public com.futu.opend.api.protobuf.QotUpdateBasicQot.Response build() {
        com.futu.opend.api.protobuf.QotUpdateBasicQot.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.opend.api.protobuf.QotUpdateBasicQot.Response buildPartial() {
        com.futu.opend.api.protobuf.QotUpdateBasicQot.Response result = new com.futu.opend.api.protobuf.QotUpdateBasicQot.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retType_ = retType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.retMsg_ = retMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (s2CBuilder_ == null) {
          result.s2C_ = s2C_;
        } else {
          result.s2C_ = s2CBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.opend.api.protobuf.QotUpdateBasicQot.Response) {
          return mergeFrom((com.futu.opend.api.protobuf.QotUpdateBasicQot.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.opend.api.protobuf.QotUpdateBasicQot.Response other) {
        if (other == com.futu.opend.api.protobuf.QotUpdateBasicQot.Response.getDefaultInstance()) return this;
        if (other.hasRetType()) {
          setRetType(other.getRetType());
        }
        if (other.hasRetMsg()) {
          bitField0_ |= 0x00000002;
          retMsg_ = other.retMsg_;
          onChanged();
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasS2C()) {
          mergeS2C(other.getS2C());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRetType()) {
          
          return false;
        }
        if (hasS2C()) {
          if (!getS2C().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.opend.api.protobuf.QotUpdateBasicQot.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.opend.api.protobuf.QotUpdateBasicQot.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int retType_ = -400;
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *RetType,返回结果
       * </pre>
       */
      public boolean hasRetType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *RetType,返回结果
       * </pre>
       */
      public int getRetType() {
        return retType_;
      }
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *RetType,返回结果
       * </pre>
       */
      public Builder setRetType(int value) {
        bitField0_ |= 0x00000001;
        retType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *RetType,返回结果
       * </pre>
       */
      public Builder clearRetType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retType_ = -400;
        onChanged();
        return this;
      }

      private java.lang.Object retMsg_ = "";
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public boolean hasRetMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public java.lang.String getRetMsg() {
        java.lang.Object ref = retMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            retMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        java.lang.Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder clearRetMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retMsg_ = getDefaultInstance().getRetMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000004;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C s2C_ = com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C, com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.Builder, com.futu.opend.api.protobuf.QotUpdateBasicQot.S2COrBuilder> s2CBuilder_;
      /**
       * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
       */
      public boolean hasS2C() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
       */
      public com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C getS2C() {
        if (s2CBuilder_ == null) {
          return s2C_;
        } else {
          return s2CBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
       */
      public Builder setS2C(com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C value) {
        if (s2CBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2C_ = value;
          onChanged();
        } else {
          s2CBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
       */
      public Builder setS2C(
          com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.Builder builderForValue) {
        if (s2CBuilder_ == null) {
          s2C_ = builderForValue.build();
          onChanged();
        } else {
          s2CBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
       */
      public Builder mergeS2C(com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C value) {
        if (s2CBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              s2C_ != com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.getDefaultInstance()) {
            s2C_ =
              com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.newBuilder(s2C_).mergeFrom(value).buildPartial();
          } else {
            s2C_ = value;
          }
          onChanged();
        } else {
          s2CBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
       */
      public Builder clearS2C() {
        if (s2CBuilder_ == null) {
          s2C_ = com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.getDefaultInstance();
          onChanged();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
       */
      public com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.Builder getS2CBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getS2CFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
       */
      public com.futu.opend.api.protobuf.QotUpdateBasicQot.S2COrBuilder getS2COrBuilder() {
        if (s2CBuilder_ != null) {
          return s2CBuilder_.getMessageOrBuilder();
        } else {
          return s2C_;
        }
      }
      /**
       * <code>optional .Qot_UpdateBasicQot.S2C s2c = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C, com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.Builder, com.futu.opend.api.protobuf.QotUpdateBasicQot.S2COrBuilder> 
          getS2CFieldBuilder() {
        if (s2CBuilder_ == null) {
          s2CBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C, com.futu.opend.api.protobuf.QotUpdateBasicQot.S2C.Builder, com.futu.opend.api.protobuf.QotUpdateBasicQot.S2COrBuilder>(
                  getS2C(),
                  getParentForChildren(),
                  isClean());
          s2C_ = null;
        }
        return s2CBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Qot_UpdateBasicQot.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdateBasicQot.Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdateBasicQot_S2C_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Qot_UpdateBasicQot_S2C_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdateBasicQot_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Qot_UpdateBasicQot_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030Qot_UpdateBasicQot.proto\022\022Qot_UpdateBa" +
      "sicQot\032\014Common.proto\032\020Qot_Common.proto\"1" +
      "\n\003S2C\022*\n\014basicQotList\030\001 \003(\0132\024.Qot_Common" +
      ".BasicQot\"h\n\010Response\022\025\n\007retType\030\001 \002(\005:\004" +
      "-400\022\016\n\006retMsg\030\002 \001(\t\022\017\n\007errCode\030\003 \001(\005\022$\n" +
      "\003s2c\030\004 \001(\0132\027.Qot_UpdateBasicQot.S2CB\035\n\033c" +
      "om.futu.opend.api.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.futu.opend.api.protobuf.Common.getDescriptor(),
          com.futu.opend.api.protobuf.QotCommon.getDescriptor(),
        }, assigner);
    internal_static_Qot_UpdateBasicQot_S2C_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Qot_UpdateBasicQot_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Qot_UpdateBasicQot_S2C_descriptor,
        new java.lang.String[] { "BasicQotList", });
    internal_static_Qot_UpdateBasicQot_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Qot_UpdateBasicQot_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Qot_UpdateBasicQot_Response_descriptor,
        new java.lang.String[] { "RetType", "RetMsg", "ErrCode", "S2C", });
    com.futu.opend.api.protobuf.Common.getDescriptor();
    com.futu.opend.api.protobuf.QotCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
