// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Qot_UpdateKL.proto

package com.futu.opend.api.protobuf;

public final class QotUpdateKL {
  private QotUpdateKL() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdateKL.S2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 rehabType = 1;</code>
     *
     * <pre>
     *Qot_Common.RehabType,复权类型
     * </pre>
     */
    boolean hasRehabType();
    /**
     * <code>required int32 rehabType = 1;</code>
     *
     * <pre>
     *Qot_Common.RehabType,复权类型
     * </pre>
     */
    int getRehabType();

    /**
     * <code>required int32 klType = 2;</code>
     *
     * <pre>
     *Qot_Common.KLType,K线类型
     * </pre>
     */
    boolean hasKlType();
    /**
     * <code>required int32 klType = 2;</code>
     *
     * <pre>
     *Qot_Common.KLType,K线类型
     * </pre>
     */
    int getKlType();

    /**
     * <code>required .Qot_Common.Security security = 3;</code>
     *
     * <pre>
     *股票
     * </pre>
     */
    boolean hasSecurity();
    /**
     * <code>required .Qot_Common.Security security = 3;</code>
     *
     * <pre>
     *股票
     * </pre>
     */
    com.futu.opend.api.protobuf.QotCommon.Security getSecurity();
    /**
     * <code>required .Qot_Common.Security security = 3;</code>
     *
     * <pre>
     *股票
     * </pre>
     */
    com.futu.opend.api.protobuf.QotCommon.SecurityOrBuilder getSecurityOrBuilder();

    /**
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     *
     * <pre>
     *推送的k线点
     * </pre>
     */
    java.util.List<com.futu.opend.api.protobuf.QotCommon.KLine> 
        getKlListList();
    /**
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     *
     * <pre>
     *推送的k线点
     * </pre>
     */
    com.futu.opend.api.protobuf.QotCommon.KLine getKlList(int index);
    /**
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     *
     * <pre>
     *推送的k线点
     * </pre>
     */
    int getKlListCount();
    /**
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     *
     * <pre>
     *推送的k线点
     * </pre>
     */
    java.util.List<? extends com.futu.opend.api.protobuf.QotCommon.KLineOrBuilder> 
        getKlListOrBuilderList();
    /**
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     *
     * <pre>
     *推送的k线点
     * </pre>
     */
    com.futu.opend.api.protobuf.QotCommon.KLineOrBuilder getKlListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Qot_UpdateKL.S2C}
   */
  public static final class S2C extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Qot_UpdateKL.S2C)
      S2COrBuilder {
    // Use S2C.newBuilder() to construct.
    private S2C(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private S2C(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final S2C defaultInstance;
    public static S2C getDefaultInstance() {
      return defaultInstance;
    }

    public S2C getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rehabType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              klType_ = input.readInt32();
              break;
            }
            case 26: {
              com.futu.opend.api.protobuf.QotCommon.Security.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = security_.toBuilder();
              }
              security_ = input.readMessage(com.futu.opend.api.protobuf.QotCommon.Security.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(security_);
                security_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                klList_ = new java.util.ArrayList<com.futu.opend.api.protobuf.QotCommon.KLine>();
                mutable_bitField0_ |= 0x00000008;
              }
              klList_.add(input.readMessage(com.futu.opend.api.protobuf.QotCommon.KLine.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          klList_ = java.util.Collections.unmodifiableList(klList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.opend.api.protobuf.QotUpdateKL.internal_static_Qot_UpdateKL_S2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.opend.api.protobuf.QotUpdateKL.internal_static_Qot_UpdateKL_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.opend.api.protobuf.QotUpdateKL.S2C.class, com.futu.opend.api.protobuf.QotUpdateKL.S2C.Builder.class);
    }

    public static com.google.protobuf.Parser<S2C> PARSER =
        new com.google.protobuf.AbstractParser<S2C>() {
      public S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<S2C> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int REHABTYPE_FIELD_NUMBER = 1;
    private int rehabType_;
    /**
     * <code>required int32 rehabType = 1;</code>
     *
     * <pre>
     *Qot_Common.RehabType,复权类型
     * </pre>
     */
    public boolean hasRehabType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rehabType = 1;</code>
     *
     * <pre>
     *Qot_Common.RehabType,复权类型
     * </pre>
     */
    public int getRehabType() {
      return rehabType_;
    }

    public static final int KLTYPE_FIELD_NUMBER = 2;
    private int klType_;
    /**
     * <code>required int32 klType = 2;</code>
     *
     * <pre>
     *Qot_Common.KLType,K线类型
     * </pre>
     */
    public boolean hasKlType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 klType = 2;</code>
     *
     * <pre>
     *Qot_Common.KLType,K线类型
     * </pre>
     */
    public int getKlType() {
      return klType_;
    }

    public static final int SECURITY_FIELD_NUMBER = 3;
    private com.futu.opend.api.protobuf.QotCommon.Security security_;
    /**
     * <code>required .Qot_Common.Security security = 3;</code>
     *
     * <pre>
     *股票
     * </pre>
     */
    public boolean hasSecurity() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .Qot_Common.Security security = 3;</code>
     *
     * <pre>
     *股票
     * </pre>
     */
    public com.futu.opend.api.protobuf.QotCommon.Security getSecurity() {
      return security_;
    }
    /**
     * <code>required .Qot_Common.Security security = 3;</code>
     *
     * <pre>
     *股票
     * </pre>
     */
    public com.futu.opend.api.protobuf.QotCommon.SecurityOrBuilder getSecurityOrBuilder() {
      return security_;
    }

    public static final int KLLIST_FIELD_NUMBER = 4;
    private java.util.List<com.futu.opend.api.protobuf.QotCommon.KLine> klList_;
    /**
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     *
     * <pre>
     *推送的k线点
     * </pre>
     */
    public java.util.List<com.futu.opend.api.protobuf.QotCommon.KLine> getKlListList() {
      return klList_;
    }
    /**
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     *
     * <pre>
     *推送的k线点
     * </pre>
     */
    public java.util.List<? extends com.futu.opend.api.protobuf.QotCommon.KLineOrBuilder> 
        getKlListOrBuilderList() {
      return klList_;
    }
    /**
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     *
     * <pre>
     *推送的k线点
     * </pre>
     */
    public int getKlListCount() {
      return klList_.size();
    }
    /**
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     *
     * <pre>
     *推送的k线点
     * </pre>
     */
    public com.futu.opend.api.protobuf.QotCommon.KLine getKlList(int index) {
      return klList_.get(index);
    }
    /**
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     *
     * <pre>
     *推送的k线点
     * </pre>
     */
    public com.futu.opend.api.protobuf.QotCommon.KLineOrBuilder getKlListOrBuilder(
        int index) {
      return klList_.get(index);
    }

    private void initFields() {
      rehabType_ = 0;
      klType_ = 0;
      security_ = com.futu.opend.api.protobuf.QotCommon.Security.getDefaultInstance();
      klList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRehabType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKlType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSecurity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSecurity().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getKlListCount(); i++) {
        if (!getKlList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rehabType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, klType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, security_);
      }
      for (int i = 0; i < klList_.size(); i++) {
        output.writeMessage(4, klList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rehabType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, klType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, security_);
      }
      for (int i = 0; i < klList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, klList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.futu.opend.api.protobuf.QotUpdateKL.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.futu.opend.api.protobuf.QotUpdateKL.S2C prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdateKL.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdateKL.S2C)
        com.futu.opend.api.protobuf.QotUpdateKL.S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.opend.api.protobuf.QotUpdateKL.internal_static_Qot_UpdateKL_S2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.opend.api.protobuf.QotUpdateKL.internal_static_Qot_UpdateKL_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.opend.api.protobuf.QotUpdateKL.S2C.class, com.futu.opend.api.protobuf.QotUpdateKL.S2C.Builder.class);
      }

      // Construct using com.futu.opend.api.protobuf.QotUpdateKL.S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSecurityFieldBuilder();
          getKlListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rehabType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        klType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (securityBuilder_ == null) {
          security_ = com.futu.opend.api.protobuf.QotCommon.Security.getDefaultInstance();
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (klListBuilder_ == null) {
          klList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          klListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.opend.api.protobuf.QotUpdateKL.internal_static_Qot_UpdateKL_S2C_descriptor;
      }

      public com.futu.opend.api.protobuf.QotUpdateKL.S2C getDefaultInstanceForType() {
        return com.futu.opend.api.protobuf.QotUpdateKL.S2C.getDefaultInstance();
      }

      public com.futu.opend.api.protobuf.QotUpdateKL.S2C build() {
        com.futu.opend.api.protobuf.QotUpdateKL.S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.opend.api.protobuf.QotUpdateKL.S2C buildPartial() {
        com.futu.opend.api.protobuf.QotUpdateKL.S2C result = new com.futu.opend.api.protobuf.QotUpdateKL.S2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rehabType_ = rehabType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.klType_ = klType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (securityBuilder_ == null) {
          result.security_ = security_;
        } else {
          result.security_ = securityBuilder_.build();
        }
        if (klListBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            klList_ = java.util.Collections.unmodifiableList(klList_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.klList_ = klList_;
        } else {
          result.klList_ = klListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.opend.api.protobuf.QotUpdateKL.S2C) {
          return mergeFrom((com.futu.opend.api.protobuf.QotUpdateKL.S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.opend.api.protobuf.QotUpdateKL.S2C other) {
        if (other == com.futu.opend.api.protobuf.QotUpdateKL.S2C.getDefaultInstance()) return this;
        if (other.hasRehabType()) {
          setRehabType(other.getRehabType());
        }
        if (other.hasKlType()) {
          setKlType(other.getKlType());
        }
        if (other.hasSecurity()) {
          mergeSecurity(other.getSecurity());
        }
        if (klListBuilder_ == null) {
          if (!other.klList_.isEmpty()) {
            if (klList_.isEmpty()) {
              klList_ = other.klList_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureKlListIsMutable();
              klList_.addAll(other.klList_);
            }
            onChanged();
          }
        } else {
          if (!other.klList_.isEmpty()) {
            if (klListBuilder_.isEmpty()) {
              klListBuilder_.dispose();
              klListBuilder_ = null;
              klList_ = other.klList_;
              bitField0_ = (bitField0_ & ~0x00000008);
              klListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getKlListFieldBuilder() : null;
            } else {
              klListBuilder_.addAllMessages(other.klList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRehabType()) {
          
          return false;
        }
        if (!hasKlType()) {
          
          return false;
        }
        if (!hasSecurity()) {
          
          return false;
        }
        if (!getSecurity().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getKlListCount(); i++) {
          if (!getKlList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.opend.api.protobuf.QotUpdateKL.S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.opend.api.protobuf.QotUpdateKL.S2C) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rehabType_ ;
      /**
       * <code>required int32 rehabType = 1;</code>
       *
       * <pre>
       *Qot_Common.RehabType,复权类型
       * </pre>
       */
      public boolean hasRehabType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rehabType = 1;</code>
       *
       * <pre>
       *Qot_Common.RehabType,复权类型
       * </pre>
       */
      public int getRehabType() {
        return rehabType_;
      }
      /**
       * <code>required int32 rehabType = 1;</code>
       *
       * <pre>
       *Qot_Common.RehabType,复权类型
       * </pre>
       */
      public Builder setRehabType(int value) {
        bitField0_ |= 0x00000001;
        rehabType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rehabType = 1;</code>
       *
       * <pre>
       *Qot_Common.RehabType,复权类型
       * </pre>
       */
      public Builder clearRehabType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rehabType_ = 0;
        onChanged();
        return this;
      }

      private int klType_ ;
      /**
       * <code>required int32 klType = 2;</code>
       *
       * <pre>
       *Qot_Common.KLType,K线类型
       * </pre>
       */
      public boolean hasKlType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 klType = 2;</code>
       *
       * <pre>
       *Qot_Common.KLType,K线类型
       * </pre>
       */
      public int getKlType() {
        return klType_;
      }
      /**
       * <code>required int32 klType = 2;</code>
       *
       * <pre>
       *Qot_Common.KLType,K线类型
       * </pre>
       */
      public Builder setKlType(int value) {
        bitField0_ |= 0x00000002;
        klType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 klType = 2;</code>
       *
       * <pre>
       *Qot_Common.KLType,K线类型
       * </pre>
       */
      public Builder clearKlType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        klType_ = 0;
        onChanged();
        return this;
      }

      private com.futu.opend.api.protobuf.QotCommon.Security security_ = com.futu.opend.api.protobuf.QotCommon.Security.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.QotCommon.Security, com.futu.opend.api.protobuf.QotCommon.Security.Builder, com.futu.opend.api.protobuf.QotCommon.SecurityOrBuilder> securityBuilder_;
      /**
       * <code>required .Qot_Common.Security security = 3;</code>
       *
       * <pre>
       *股票
       * </pre>
       */
      public boolean hasSecurity() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .Qot_Common.Security security = 3;</code>
       *
       * <pre>
       *股票
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.Security getSecurity() {
        if (securityBuilder_ == null) {
          return security_;
        } else {
          return securityBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Qot_Common.Security security = 3;</code>
       *
       * <pre>
       *股票
       * </pre>
       */
      public Builder setSecurity(com.futu.opend.api.protobuf.QotCommon.Security value) {
        if (securityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          security_ = value;
          onChanged();
        } else {
          securityBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .Qot_Common.Security security = 3;</code>
       *
       * <pre>
       *股票
       * </pre>
       */
      public Builder setSecurity(
          com.futu.opend.api.protobuf.QotCommon.Security.Builder builderForValue) {
        if (securityBuilder_ == null) {
          security_ = builderForValue.build();
          onChanged();
        } else {
          securityBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .Qot_Common.Security security = 3;</code>
       *
       * <pre>
       *股票
       * </pre>
       */
      public Builder mergeSecurity(com.futu.opend.api.protobuf.QotCommon.Security value) {
        if (securityBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              security_ != com.futu.opend.api.protobuf.QotCommon.Security.getDefaultInstance()) {
            security_ =
              com.futu.opend.api.protobuf.QotCommon.Security.newBuilder(security_).mergeFrom(value).buildPartial();
          } else {
            security_ = value;
          }
          onChanged();
        } else {
          securityBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .Qot_Common.Security security = 3;</code>
       *
       * <pre>
       *股票
       * </pre>
       */
      public Builder clearSecurity() {
        if (securityBuilder_ == null) {
          security_ = com.futu.opend.api.protobuf.QotCommon.Security.getDefaultInstance();
          onChanged();
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .Qot_Common.Security security = 3;</code>
       *
       * <pre>
       *股票
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.Security.Builder getSecurityBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSecurityFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Qot_Common.Security security = 3;</code>
       *
       * <pre>
       *股票
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.SecurityOrBuilder getSecurityOrBuilder() {
        if (securityBuilder_ != null) {
          return securityBuilder_.getMessageOrBuilder();
        } else {
          return security_;
        }
      }
      /**
       * <code>required .Qot_Common.Security security = 3;</code>
       *
       * <pre>
       *股票
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.QotCommon.Security, com.futu.opend.api.protobuf.QotCommon.Security.Builder, com.futu.opend.api.protobuf.QotCommon.SecurityOrBuilder> 
          getSecurityFieldBuilder() {
        if (securityBuilder_ == null) {
          securityBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.futu.opend.api.protobuf.QotCommon.Security, com.futu.opend.api.protobuf.QotCommon.Security.Builder, com.futu.opend.api.protobuf.QotCommon.SecurityOrBuilder>(
                  getSecurity(),
                  getParentForChildren(),
                  isClean());
          security_ = null;
        }
        return securityBuilder_;
      }

      private java.util.List<com.futu.opend.api.protobuf.QotCommon.KLine> klList_ =
        java.util.Collections.emptyList();
      private void ensureKlListIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          klList_ = new java.util.ArrayList<com.futu.opend.api.protobuf.QotCommon.KLine>(klList_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.futu.opend.api.protobuf.QotCommon.KLine, com.futu.opend.api.protobuf.QotCommon.KLine.Builder, com.futu.opend.api.protobuf.QotCommon.KLineOrBuilder> klListBuilder_;

      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public java.util.List<com.futu.opend.api.protobuf.QotCommon.KLine> getKlListList() {
        if (klListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(klList_);
        } else {
          return klListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public int getKlListCount() {
        if (klListBuilder_ == null) {
          return klList_.size();
        } else {
          return klListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.KLine getKlList(int index) {
        if (klListBuilder_ == null) {
          return klList_.get(index);
        } else {
          return klListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public Builder setKlList(
          int index, com.futu.opend.api.protobuf.QotCommon.KLine value) {
        if (klListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKlListIsMutable();
          klList_.set(index, value);
          onChanged();
        } else {
          klListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public Builder setKlList(
          int index, com.futu.opend.api.protobuf.QotCommon.KLine.Builder builderForValue) {
        if (klListBuilder_ == null) {
          ensureKlListIsMutable();
          klList_.set(index, builderForValue.build());
          onChanged();
        } else {
          klListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public Builder addKlList(com.futu.opend.api.protobuf.QotCommon.KLine value) {
        if (klListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKlListIsMutable();
          klList_.add(value);
          onChanged();
        } else {
          klListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public Builder addKlList(
          int index, com.futu.opend.api.protobuf.QotCommon.KLine value) {
        if (klListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKlListIsMutable();
          klList_.add(index, value);
          onChanged();
        } else {
          klListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public Builder addKlList(
          com.futu.opend.api.protobuf.QotCommon.KLine.Builder builderForValue) {
        if (klListBuilder_ == null) {
          ensureKlListIsMutable();
          klList_.add(builderForValue.build());
          onChanged();
        } else {
          klListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public Builder addKlList(
          int index, com.futu.opend.api.protobuf.QotCommon.KLine.Builder builderForValue) {
        if (klListBuilder_ == null) {
          ensureKlListIsMutable();
          klList_.add(index, builderForValue.build());
          onChanged();
        } else {
          klListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public Builder addAllKlList(
          java.lang.Iterable<? extends com.futu.opend.api.protobuf.QotCommon.KLine> values) {
        if (klListBuilder_ == null) {
          ensureKlListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, klList_);
          onChanged();
        } else {
          klListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public Builder clearKlList() {
        if (klListBuilder_ == null) {
          klList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          klListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public Builder removeKlList(int index) {
        if (klListBuilder_ == null) {
          ensureKlListIsMutable();
          klList_.remove(index);
          onChanged();
        } else {
          klListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.KLine.Builder getKlListBuilder(
          int index) {
        return getKlListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.KLineOrBuilder getKlListOrBuilder(
          int index) {
        if (klListBuilder_ == null) {
          return klList_.get(index);  } else {
          return klListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public java.util.List<? extends com.futu.opend.api.protobuf.QotCommon.KLineOrBuilder> 
           getKlListOrBuilderList() {
        if (klListBuilder_ != null) {
          return klListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(klList_);
        }
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.KLine.Builder addKlListBuilder() {
        return getKlListFieldBuilder().addBuilder(
            com.futu.opend.api.protobuf.QotCommon.KLine.getDefaultInstance());
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public com.futu.opend.api.protobuf.QotCommon.KLine.Builder addKlListBuilder(
          int index) {
        return getKlListFieldBuilder().addBuilder(
            index, com.futu.opend.api.protobuf.QotCommon.KLine.getDefaultInstance());
      }
      /**
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       *
       * <pre>
       *推送的k线点
       * </pre>
       */
      public java.util.List<com.futu.opend.api.protobuf.QotCommon.KLine.Builder> 
           getKlListBuilderList() {
        return getKlListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.futu.opend.api.protobuf.QotCommon.KLine, com.futu.opend.api.protobuf.QotCommon.KLine.Builder, com.futu.opend.api.protobuf.QotCommon.KLineOrBuilder> 
          getKlListFieldBuilder() {
        if (klListBuilder_ == null) {
          klListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.futu.opend.api.protobuf.QotCommon.KLine, com.futu.opend.api.protobuf.QotCommon.KLine.Builder, com.futu.opend.api.protobuf.QotCommon.KLineOrBuilder>(
                  klList_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          klList_ = null;
        }
        return klListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Qot_UpdateKL.S2C)
    }

    static {
      defaultInstance = new S2C(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdateKL.S2C)
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdateKL.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *RetType,返回结果
     * </pre>
     */
    boolean hasRetType();
    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *RetType,返回结果
     * </pre>
     */
    int getRetType();

    /**
     * <code>optional string retMsg = 2;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();

    /**
     * <code>optional int32 errCode = 3;</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    int getErrCode();

    /**
     * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
     */
    boolean hasS2C();
    /**
     * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
     */
    com.futu.opend.api.protobuf.QotUpdateKL.S2C getS2C();
    /**
     * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
     */
    com.futu.opend.api.protobuf.QotUpdateKL.S2COrBuilder getS2COrBuilder();
  }
  /**
   * Protobuf type {@code Qot_UpdateKL.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Qot_UpdateKL.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              retType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              retMsg_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errCode_ = input.readInt32();
              break;
            }
            case 34: {
              com.futu.opend.api.protobuf.QotUpdateKL.S2C.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = s2C_.toBuilder();
              }
              s2C_ = input.readMessage(com.futu.opend.api.protobuf.QotUpdateKL.S2C.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2C_);
                s2C_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.opend.api.protobuf.QotUpdateKL.internal_static_Qot_UpdateKL_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.opend.api.protobuf.QotUpdateKL.internal_static_Qot_UpdateKL_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.opend.api.protobuf.QotUpdateKL.Response.class, com.futu.opend.api.protobuf.QotUpdateKL.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RETTYPE_FIELD_NUMBER = 1;
    private int retType_;
    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *RetType,返回结果
     * </pre>
     */
    public boolean hasRetType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *RetType,返回结果
     * </pre>
     */
    public int getRetType() {
      return retType_;
    }

    public static final int RETMSG_FIELD_NUMBER = 2;
    private java.lang.Object retMsg_;
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int S2C_FIELD_NUMBER = 4;
    private com.futu.opend.api.protobuf.QotUpdateKL.S2C s2C_;
    /**
     * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
     */
    public boolean hasS2C() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
     */
    public com.futu.opend.api.protobuf.QotUpdateKL.S2C getS2C() {
      return s2C_;
    }
    /**
     * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
     */
    public com.futu.opend.api.protobuf.QotUpdateKL.S2COrBuilder getS2COrBuilder() {
      return s2C_;
    }

    private void initFields() {
      retType_ = -400;
      retMsg_ = "";
      errCode_ = 0;
      s2C_ = com.futu.opend.api.protobuf.QotUpdateKL.S2C.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRetType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasS2C()) {
        if (!getS2C().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, retType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRetMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, s2C_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRetMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, s2C_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.futu.opend.api.protobuf.QotUpdateKL.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.QotUpdateKL.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.futu.opend.api.protobuf.QotUpdateKL.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdateKL.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdateKL.Response)
        com.futu.opend.api.protobuf.QotUpdateKL.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.opend.api.protobuf.QotUpdateKL.internal_static_Qot_UpdateKL_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.opend.api.protobuf.QotUpdateKL.internal_static_Qot_UpdateKL_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.opend.api.protobuf.QotUpdateKL.Response.class, com.futu.opend.api.protobuf.QotUpdateKL.Response.Builder.class);
      }

      // Construct using com.futu.opend.api.protobuf.QotUpdateKL.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getS2CFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        retType_ = -400;
        bitField0_ = (bitField0_ & ~0x00000001);
        retMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (s2CBuilder_ == null) {
          s2C_ = com.futu.opend.api.protobuf.QotUpdateKL.S2C.getDefaultInstance();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.opend.api.protobuf.QotUpdateKL.internal_static_Qot_UpdateKL_Response_descriptor;
      }

      public com.futu.opend.api.protobuf.QotUpdateKL.Response getDefaultInstanceForType() {
        return com.futu.opend.api.protobuf.QotUpdateKL.Response.getDefaultInstance();
      }

      public com.futu.opend.api.protobuf.QotUpdateKL.Response build() {
        com.futu.opend.api.protobuf.QotUpdateKL.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.opend.api.protobuf.QotUpdateKL.Response buildPartial() {
        com.futu.opend.api.protobuf.QotUpdateKL.Response result = new com.futu.opend.api.protobuf.QotUpdateKL.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retType_ = retType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.retMsg_ = retMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (s2CBuilder_ == null) {
          result.s2C_ = s2C_;
        } else {
          result.s2C_ = s2CBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.opend.api.protobuf.QotUpdateKL.Response) {
          return mergeFrom((com.futu.opend.api.protobuf.QotUpdateKL.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.opend.api.protobuf.QotUpdateKL.Response other) {
        if (other == com.futu.opend.api.protobuf.QotUpdateKL.Response.getDefaultInstance()) return this;
        if (other.hasRetType()) {
          setRetType(other.getRetType());
        }
        if (other.hasRetMsg()) {
          bitField0_ |= 0x00000002;
          retMsg_ = other.retMsg_;
          onChanged();
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasS2C()) {
          mergeS2C(other.getS2C());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRetType()) {
          
          return false;
        }
        if (hasS2C()) {
          if (!getS2C().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.opend.api.protobuf.QotUpdateKL.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.opend.api.protobuf.QotUpdateKL.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int retType_ = -400;
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *RetType,返回结果
       * </pre>
       */
      public boolean hasRetType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *RetType,返回结果
       * </pre>
       */
      public int getRetType() {
        return retType_;
      }
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *RetType,返回结果
       * </pre>
       */
      public Builder setRetType(int value) {
        bitField0_ |= 0x00000001;
        retType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *RetType,返回结果
       * </pre>
       */
      public Builder clearRetType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retType_ = -400;
        onChanged();
        return this;
      }

      private java.lang.Object retMsg_ = "";
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public boolean hasRetMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public java.lang.String getRetMsg() {
        java.lang.Object ref = retMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            retMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        java.lang.Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder clearRetMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retMsg_ = getDefaultInstance().getRetMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000004;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private com.futu.opend.api.protobuf.QotUpdateKL.S2C s2C_ = com.futu.opend.api.protobuf.QotUpdateKL.S2C.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.QotUpdateKL.S2C, com.futu.opend.api.protobuf.QotUpdateKL.S2C.Builder, com.futu.opend.api.protobuf.QotUpdateKL.S2COrBuilder> s2CBuilder_;
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public boolean hasS2C() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public com.futu.opend.api.protobuf.QotUpdateKL.S2C getS2C() {
        if (s2CBuilder_ == null) {
          return s2C_;
        } else {
          return s2CBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public Builder setS2C(com.futu.opend.api.protobuf.QotUpdateKL.S2C value) {
        if (s2CBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2C_ = value;
          onChanged();
        } else {
          s2CBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public Builder setS2C(
          com.futu.opend.api.protobuf.QotUpdateKL.S2C.Builder builderForValue) {
        if (s2CBuilder_ == null) {
          s2C_ = builderForValue.build();
          onChanged();
        } else {
          s2CBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public Builder mergeS2C(com.futu.opend.api.protobuf.QotUpdateKL.S2C value) {
        if (s2CBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              s2C_ != com.futu.opend.api.protobuf.QotUpdateKL.S2C.getDefaultInstance()) {
            s2C_ =
              com.futu.opend.api.protobuf.QotUpdateKL.S2C.newBuilder(s2C_).mergeFrom(value).buildPartial();
          } else {
            s2C_ = value;
          }
          onChanged();
        } else {
          s2CBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public Builder clearS2C() {
        if (s2CBuilder_ == null) {
          s2C_ = com.futu.opend.api.protobuf.QotUpdateKL.S2C.getDefaultInstance();
          onChanged();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public com.futu.opend.api.protobuf.QotUpdateKL.S2C.Builder getS2CBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getS2CFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public com.futu.opend.api.protobuf.QotUpdateKL.S2COrBuilder getS2COrBuilder() {
        if (s2CBuilder_ != null) {
          return s2CBuilder_.getMessageOrBuilder();
        } else {
          return s2C_;
        }
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.QotUpdateKL.S2C, com.futu.opend.api.protobuf.QotUpdateKL.S2C.Builder, com.futu.opend.api.protobuf.QotUpdateKL.S2COrBuilder> 
          getS2CFieldBuilder() {
        if (s2CBuilder_ == null) {
          s2CBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.futu.opend.api.protobuf.QotUpdateKL.S2C, com.futu.opend.api.protobuf.QotUpdateKL.S2C.Builder, com.futu.opend.api.protobuf.QotUpdateKL.S2COrBuilder>(
                  getS2C(),
                  getParentForChildren(),
                  isClean());
          s2C_ = null;
        }
        return s2CBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Qot_UpdateKL.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdateKL.Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdateKL_S2C_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Qot_UpdateKL_S2C_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdateKL_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Qot_UpdateKL_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Qot_UpdateKL.proto\022\014Qot_UpdateKL\032\014Comm" +
      "on.proto\032\020Qot_Common.proto\"s\n\003S2C\022\021\n\treh" +
      "abType\030\001 \002(\005\022\016\n\006klType\030\002 \002(\005\022&\n\010security" +
      "\030\003 \002(\0132\024.Qot_Common.Security\022!\n\006klList\030\004" +
      " \003(\0132\021.Qot_Common.KLine\"b\n\010Response\022\025\n\007r" +
      "etType\030\001 \002(\005:\004-400\022\016\n\006retMsg\030\002 \001(\t\022\017\n\007er" +
      "rCode\030\003 \001(\005\022\036\n\003s2c\030\004 \001(\0132\021.Qot_UpdateKL." +
      "S2CB\035\n\033com.futu.opend.api.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.futu.opend.api.protobuf.Common.getDescriptor(),
          com.futu.opend.api.protobuf.QotCommon.getDescriptor(),
        }, assigner);
    internal_static_Qot_UpdateKL_S2C_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Qot_UpdateKL_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Qot_UpdateKL_S2C_descriptor,
        new java.lang.String[] { "RehabType", "KlType", "Security", "KlList", });
    internal_static_Qot_UpdateKL_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Qot_UpdateKL_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Qot_UpdateKL_Response_descriptor,
        new java.lang.String[] { "RetType", "RetMsg", "ErrCode", "S2C", });
    com.futu.opend.api.protobuf.Common.getDescriptor();
    com.futu.opend.api.protobuf.QotCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
