// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Trd_Notify.proto

package com.futu.opend.api.protobuf;

public final class TrdNotify {
  private TrdNotify() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Trd_Notify.S2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Trd_Common.TrdHeader header = 1;</code>
     *
     * <pre>
     *交易公共参数头
     * </pre>
     */
    boolean hasHeader();
    /**
     * <code>required .Trd_Common.TrdHeader header = 1;</code>
     *
     * <pre>
     *交易公共参数头
     * </pre>
     */
    com.futu.opend.api.protobuf.TrdCommon.TrdHeader getHeader();
    /**
     * <code>required .Trd_Common.TrdHeader header = 1;</code>
     *
     * <pre>
     *交易公共参数头
     * </pre>
     */
    com.futu.opend.api.protobuf.TrdCommon.TrdHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *通知类型，后边再补充
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *通知类型，后边再补充
     * </pre>
     */
    int getType();
  }
  /**
   * Protobuf type {@code Trd_Notify.S2C}
   */
  public static final class S2C extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Trd_Notify.S2C)
      S2COrBuilder {
    // Use S2C.newBuilder() to construct.
    private S2C(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private S2C(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final S2C defaultInstance;
    public static S2C getDefaultInstance() {
      return defaultInstance;
    }

    public S2C getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.futu.opend.api.protobuf.TrdCommon.TrdHeader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.futu.opend.api.protobuf.TrdCommon.TrdHeader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.opend.api.protobuf.TrdNotify.internal_static_Trd_Notify_S2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.opend.api.protobuf.TrdNotify.internal_static_Trd_Notify_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.opend.api.protobuf.TrdNotify.S2C.class, com.futu.opend.api.protobuf.TrdNotify.S2C.Builder.class);
    }

    public static com.google.protobuf.Parser<S2C> PARSER =
        new com.google.protobuf.AbstractParser<S2C>() {
      public S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<S2C> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private com.futu.opend.api.protobuf.TrdCommon.TrdHeader header_;
    /**
     * <code>required .Trd_Common.TrdHeader header = 1;</code>
     *
     * <pre>
     *交易公共参数头
     * </pre>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Trd_Common.TrdHeader header = 1;</code>
     *
     * <pre>
     *交易公共参数头
     * </pre>
     */
    public com.futu.opend.api.protobuf.TrdCommon.TrdHeader getHeader() {
      return header_;
    }
    /**
     * <code>required .Trd_Common.TrdHeader header = 1;</code>
     *
     * <pre>
     *交易公共参数头
     * </pre>
     */
    public com.futu.opend.api.protobuf.TrdCommon.TrdHeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *通知类型，后边再补充
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *通知类型，后边再补充
     * </pre>
     */
    public int getType() {
      return type_;
    }

    private void initFields() {
      header_ = com.futu.opend.api.protobuf.TrdCommon.TrdHeader.getDefaultInstance();
      type_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.futu.opend.api.protobuf.TrdNotify.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.futu.opend.api.protobuf.TrdNotify.S2C prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Trd_Notify.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Trd_Notify.S2C)
        com.futu.opend.api.protobuf.TrdNotify.S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.opend.api.protobuf.TrdNotify.internal_static_Trd_Notify_S2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.opend.api.protobuf.TrdNotify.internal_static_Trd_Notify_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.opend.api.protobuf.TrdNotify.S2C.class, com.futu.opend.api.protobuf.TrdNotify.S2C.Builder.class);
      }

      // Construct using com.futu.opend.api.protobuf.TrdNotify.S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = com.futu.opend.api.protobuf.TrdCommon.TrdHeader.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.opend.api.protobuf.TrdNotify.internal_static_Trd_Notify_S2C_descriptor;
      }

      public com.futu.opend.api.protobuf.TrdNotify.S2C getDefaultInstanceForType() {
        return com.futu.opend.api.protobuf.TrdNotify.S2C.getDefaultInstance();
      }

      public com.futu.opend.api.protobuf.TrdNotify.S2C build() {
        com.futu.opend.api.protobuf.TrdNotify.S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.opend.api.protobuf.TrdNotify.S2C buildPartial() {
        com.futu.opend.api.protobuf.TrdNotify.S2C result = new com.futu.opend.api.protobuf.TrdNotify.S2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.opend.api.protobuf.TrdNotify.S2C) {
          return mergeFrom((com.futu.opend.api.protobuf.TrdNotify.S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.opend.api.protobuf.TrdNotify.S2C other) {
        if (other == com.futu.opend.api.protobuf.TrdNotify.S2C.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!getHeader().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.opend.api.protobuf.TrdNotify.S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.opend.api.protobuf.TrdNotify.S2C) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.futu.opend.api.protobuf.TrdCommon.TrdHeader header_ = com.futu.opend.api.protobuf.TrdCommon.TrdHeader.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.TrdCommon.TrdHeader, com.futu.opend.api.protobuf.TrdCommon.TrdHeader.Builder, com.futu.opend.api.protobuf.TrdCommon.TrdHeaderOrBuilder> headerBuilder_;
      /**
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       *
       * <pre>
       *交易公共参数头
       * </pre>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       *
       * <pre>
       *交易公共参数头
       * </pre>
       */
      public com.futu.opend.api.protobuf.TrdCommon.TrdHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       *
       * <pre>
       *交易公共参数头
       * </pre>
       */
      public Builder setHeader(com.futu.opend.api.protobuf.TrdCommon.TrdHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       *
       * <pre>
       *交易公共参数头
       * </pre>
       */
      public Builder setHeader(
          com.futu.opend.api.protobuf.TrdCommon.TrdHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       *
       * <pre>
       *交易公共参数头
       * </pre>
       */
      public Builder mergeHeader(com.futu.opend.api.protobuf.TrdCommon.TrdHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != com.futu.opend.api.protobuf.TrdCommon.TrdHeader.getDefaultInstance()) {
            header_ =
              com.futu.opend.api.protobuf.TrdCommon.TrdHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       *
       * <pre>
       *交易公共参数头
       * </pre>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = com.futu.opend.api.protobuf.TrdCommon.TrdHeader.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       *
       * <pre>
       *交易公共参数头
       * </pre>
       */
      public com.futu.opend.api.protobuf.TrdCommon.TrdHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       *
       * <pre>
       *交易公共参数头
       * </pre>
       */
      public com.futu.opend.api.protobuf.TrdCommon.TrdHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       *
       * <pre>
       *交易公共参数头
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.TrdCommon.TrdHeader, com.futu.opend.api.protobuf.TrdCommon.TrdHeader.Builder, com.futu.opend.api.protobuf.TrdCommon.TrdHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.futu.opend.api.protobuf.TrdCommon.TrdHeader, com.futu.opend.api.protobuf.TrdCommon.TrdHeader.Builder, com.futu.opend.api.protobuf.TrdCommon.TrdHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private int type_ ;
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *通知类型，后边再补充
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *通知类型，后边再补充
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *通知类型，后边再补充
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *通知类型，后边再补充
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Trd_Notify.S2C)
    }

    static {
      defaultInstance = new S2C(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Trd_Notify.S2C)
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Trd_Notify.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *以下3个字段每条协议都有，注释说明在InitConnect.proto中
     * </pre>
     */
    boolean hasRetType();
    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *以下3个字段每条协议都有，注释说明在InitConnect.proto中
     * </pre>
     */
    int getRetType();

    /**
     * <code>optional string retMsg = 2;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();

    /**
     * <code>optional int32 errCode = 3;</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    int getErrCode();

    /**
     * <code>optional .Trd_Notify.S2C s2c = 4;</code>
     */
    boolean hasS2C();
    /**
     * <code>optional .Trd_Notify.S2C s2c = 4;</code>
     */
    com.futu.opend.api.protobuf.TrdNotify.S2C getS2C();
    /**
     * <code>optional .Trd_Notify.S2C s2c = 4;</code>
     */
    com.futu.opend.api.protobuf.TrdNotify.S2COrBuilder getS2COrBuilder();
  }
  /**
   * Protobuf type {@code Trd_Notify.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Trd_Notify.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              retType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              retMsg_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errCode_ = input.readInt32();
              break;
            }
            case 34: {
              com.futu.opend.api.protobuf.TrdNotify.S2C.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = s2C_.toBuilder();
              }
              s2C_ = input.readMessage(com.futu.opend.api.protobuf.TrdNotify.S2C.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2C_);
                s2C_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.opend.api.protobuf.TrdNotify.internal_static_Trd_Notify_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.opend.api.protobuf.TrdNotify.internal_static_Trd_Notify_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.opend.api.protobuf.TrdNotify.Response.class, com.futu.opend.api.protobuf.TrdNotify.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RETTYPE_FIELD_NUMBER = 1;
    private int retType_;
    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *以下3个字段每条协议都有，注释说明在InitConnect.proto中
     * </pre>
     */
    public boolean hasRetType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 retType = 1 [default = -400];</code>
     *
     * <pre>
     *以下3个字段每条协议都有，注释说明在InitConnect.proto中
     * </pre>
     */
    public int getRetType() {
      return retType_;
    }

    public static final int RETMSG_FIELD_NUMBER = 2;
    private java.lang.Object retMsg_;
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int S2C_FIELD_NUMBER = 4;
    private com.futu.opend.api.protobuf.TrdNotify.S2C s2C_;
    /**
     * <code>optional .Trd_Notify.S2C s2c = 4;</code>
     */
    public boolean hasS2C() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Trd_Notify.S2C s2c = 4;</code>
     */
    public com.futu.opend.api.protobuf.TrdNotify.S2C getS2C() {
      return s2C_;
    }
    /**
     * <code>optional .Trd_Notify.S2C s2c = 4;</code>
     */
    public com.futu.opend.api.protobuf.TrdNotify.S2COrBuilder getS2COrBuilder() {
      return s2C_;
    }

    private void initFields() {
      retType_ = -400;
      retMsg_ = "";
      errCode_ = 0;
      s2C_ = com.futu.opend.api.protobuf.TrdNotify.S2C.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRetType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasS2C()) {
        if (!getS2C().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, retType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRetMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, s2C_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRetMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, s2C_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.futu.opend.api.protobuf.TrdNotify.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.futu.opend.api.protobuf.TrdNotify.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.futu.opend.api.protobuf.TrdNotify.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Trd_Notify.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Trd_Notify.Response)
        com.futu.opend.api.protobuf.TrdNotify.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.opend.api.protobuf.TrdNotify.internal_static_Trd_Notify_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.opend.api.protobuf.TrdNotify.internal_static_Trd_Notify_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.opend.api.protobuf.TrdNotify.Response.class, com.futu.opend.api.protobuf.TrdNotify.Response.Builder.class);
      }

      // Construct using com.futu.opend.api.protobuf.TrdNotify.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getS2CFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        retType_ = -400;
        bitField0_ = (bitField0_ & ~0x00000001);
        retMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (s2CBuilder_ == null) {
          s2C_ = com.futu.opend.api.protobuf.TrdNotify.S2C.getDefaultInstance();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.opend.api.protobuf.TrdNotify.internal_static_Trd_Notify_Response_descriptor;
      }

      public com.futu.opend.api.protobuf.TrdNotify.Response getDefaultInstanceForType() {
        return com.futu.opend.api.protobuf.TrdNotify.Response.getDefaultInstance();
      }

      public com.futu.opend.api.protobuf.TrdNotify.Response build() {
        com.futu.opend.api.protobuf.TrdNotify.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.opend.api.protobuf.TrdNotify.Response buildPartial() {
        com.futu.opend.api.protobuf.TrdNotify.Response result = new com.futu.opend.api.protobuf.TrdNotify.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retType_ = retType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.retMsg_ = retMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (s2CBuilder_ == null) {
          result.s2C_ = s2C_;
        } else {
          result.s2C_ = s2CBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.opend.api.protobuf.TrdNotify.Response) {
          return mergeFrom((com.futu.opend.api.protobuf.TrdNotify.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.opend.api.protobuf.TrdNotify.Response other) {
        if (other == com.futu.opend.api.protobuf.TrdNotify.Response.getDefaultInstance()) return this;
        if (other.hasRetType()) {
          setRetType(other.getRetType());
        }
        if (other.hasRetMsg()) {
          bitField0_ |= 0x00000002;
          retMsg_ = other.retMsg_;
          onChanged();
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasS2C()) {
          mergeS2C(other.getS2C());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRetType()) {
          
          return false;
        }
        if (hasS2C()) {
          if (!getS2C().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.opend.api.protobuf.TrdNotify.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.opend.api.protobuf.TrdNotify.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int retType_ = -400;
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *以下3个字段每条协议都有，注释说明在InitConnect.proto中
       * </pre>
       */
      public boolean hasRetType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *以下3个字段每条协议都有，注释说明在InitConnect.proto中
       * </pre>
       */
      public int getRetType() {
        return retType_;
      }
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *以下3个字段每条协议都有，注释说明在InitConnect.proto中
       * </pre>
       */
      public Builder setRetType(int value) {
        bitField0_ |= 0x00000001;
        retType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 retType = 1 [default = -400];</code>
       *
       * <pre>
       *以下3个字段每条协议都有，注释说明在InitConnect.proto中
       * </pre>
       */
      public Builder clearRetType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retType_ = -400;
        onChanged();
        return this;
      }

      private java.lang.Object retMsg_ = "";
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public boolean hasRetMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public java.lang.String getRetMsg() {
        java.lang.Object ref = retMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            retMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        java.lang.Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder clearRetMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retMsg_ = getDefaultInstance().getRetMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000004;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private com.futu.opend.api.protobuf.TrdNotify.S2C s2C_ = com.futu.opend.api.protobuf.TrdNotify.S2C.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.TrdNotify.S2C, com.futu.opend.api.protobuf.TrdNotify.S2C.Builder, com.futu.opend.api.protobuf.TrdNotify.S2COrBuilder> s2CBuilder_;
      /**
       * <code>optional .Trd_Notify.S2C s2c = 4;</code>
       */
      public boolean hasS2C() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Trd_Notify.S2C s2c = 4;</code>
       */
      public com.futu.opend.api.protobuf.TrdNotify.S2C getS2C() {
        if (s2CBuilder_ == null) {
          return s2C_;
        } else {
          return s2CBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Trd_Notify.S2C s2c = 4;</code>
       */
      public Builder setS2C(com.futu.opend.api.protobuf.TrdNotify.S2C value) {
        if (s2CBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2C_ = value;
          onChanged();
        } else {
          s2CBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Trd_Notify.S2C s2c = 4;</code>
       */
      public Builder setS2C(
          com.futu.opend.api.protobuf.TrdNotify.S2C.Builder builderForValue) {
        if (s2CBuilder_ == null) {
          s2C_ = builderForValue.build();
          onChanged();
        } else {
          s2CBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Trd_Notify.S2C s2c = 4;</code>
       */
      public Builder mergeS2C(com.futu.opend.api.protobuf.TrdNotify.S2C value) {
        if (s2CBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              s2C_ != com.futu.opend.api.protobuf.TrdNotify.S2C.getDefaultInstance()) {
            s2C_ =
              com.futu.opend.api.protobuf.TrdNotify.S2C.newBuilder(s2C_).mergeFrom(value).buildPartial();
          } else {
            s2C_ = value;
          }
          onChanged();
        } else {
          s2CBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Trd_Notify.S2C s2c = 4;</code>
       */
      public Builder clearS2C() {
        if (s2CBuilder_ == null) {
          s2C_ = com.futu.opend.api.protobuf.TrdNotify.S2C.getDefaultInstance();
          onChanged();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Trd_Notify.S2C s2c = 4;</code>
       */
      public com.futu.opend.api.protobuf.TrdNotify.S2C.Builder getS2CBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getS2CFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Trd_Notify.S2C s2c = 4;</code>
       */
      public com.futu.opend.api.protobuf.TrdNotify.S2COrBuilder getS2COrBuilder() {
        if (s2CBuilder_ != null) {
          return s2CBuilder_.getMessageOrBuilder();
        } else {
          return s2C_;
        }
      }
      /**
       * <code>optional .Trd_Notify.S2C s2c = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.futu.opend.api.protobuf.TrdNotify.S2C, com.futu.opend.api.protobuf.TrdNotify.S2C.Builder, com.futu.opend.api.protobuf.TrdNotify.S2COrBuilder> 
          getS2CFieldBuilder() {
        if (s2CBuilder_ == null) {
          s2CBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.futu.opend.api.protobuf.TrdNotify.S2C, com.futu.opend.api.protobuf.TrdNotify.S2C.Builder, com.futu.opend.api.protobuf.TrdNotify.S2COrBuilder>(
                  getS2C(),
                  getParentForChildren(),
                  isClean());
          s2C_ = null;
        }
        return s2CBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Trd_Notify.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Trd_Notify.Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Trd_Notify_S2C_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Trd_Notify_S2C_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Trd_Notify_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Trd_Notify_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Trd_Notify.proto\022\nTrd_Notify\032\014Common.p" +
      "roto\032\020Trd_Common.proto\":\n\003S2C\022%\n\006header\030" +
      "\001 \002(\0132\025.Trd_Common.TrdHeader\022\014\n\004type\030\002 \002" +
      "(\005\"`\n\010Response\022\025\n\007retType\030\001 \002(\005:\004-400\022\016\n" +
      "\006retMsg\030\002 \001(\t\022\017\n\007errCode\030\003 \001(\005\022\034\n\003s2c\030\004 " +
      "\001(\0132\017.Trd_Notify.S2CB\035\n\033com.futu.opend.a" +
      "pi.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.futu.opend.api.protobuf.Common.getDescriptor(),
          com.futu.opend.api.protobuf.TrdCommon.getDescriptor(),
        }, assigner);
    internal_static_Trd_Notify_S2C_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Trd_Notify_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Trd_Notify_S2C_descriptor,
        new java.lang.String[] { "Header", "Type", });
    internal_static_Trd_Notify_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Trd_Notify_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Trd_Notify_Response_descriptor,
        new java.lang.String[] { "RetType", "RetMsg", "ErrCode", "S2C", });
    com.futu.opend.api.protobuf.Common.getDescriptor();
    com.futu.opend.api.protobuf.TrdCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
